### ISSUE TITLE
Upload HydroSheds high-res DEM to GeoServer (1)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#1]
Confirm with Richard which DEM is used for basin delineation.

**Comment by tlogan2000** [comment]
15 and 30 arc second resolultions are ok with everyone I imagine?  3 sec is available but only in a bunch of tiles

**Comment by huard** [comment]
@richardarsenault ?

Note that the project officially starts in July, I'm just preparing the groundwork.

**Comment by tomLandry** [comment]
We are currently working on to advance, in general, upload to GeoServer tasks of PAVICS (@Zvax). Note that having said DEM already available would help to start the UI aspects. Do we need/want to visualize these DEMS (flattened WCS)? Is it data meant mainly as input to processes? Is is restricted in any form?

**Comment by huard** [comment]
Yes, ideally we would visualize the DEM as the base layer or an overlay. 
Also meant as an input to the delineation process and the watershed properties process. 
Restricted? If you mean access permissions, no, we'll chose an open dataset.

**Comment by Zeitsperre** [comment]
@tomLandry in terms of data use restriction, I'm not sure exactly what the restrictions are. There may be some restrictions on how we distribute it to third parties. Not a lawyer but here's the legal notice http://hydrosheds.org/license.

As a heads up in terms of coverage, the data set doesn't rise above 60N for the NA region. I imagine this is fine for most studies but not for Yukon or Northern Quebec analyses. See below:

![screenshot_2018-06-20_11-53-01](https://user-images.githubusercontent.com/10819524/41670046-421fac30-7481-11e8-9d21-230518ae33b6.png)

On a related note, HydroSHEDS also maintains the newer HydroBASINS project which has multi-level hydrological basins in vector format (with and without lakes). Coverage available for all of NA region. See below:

![screenshot_2018-06-20_12-05-35](https://user-images.githubusercontent.com/10819524/41670468-6126890e-7482-11e8-9ee9-829aafa479e6.png)

In any case, I have the data now. @huard Where would you like me to integrate the data (Ouranos or CRIM internal)?

**Comment by huard** [comment]
I suggest CRIM first then once things are more stable copy things to Ouranos.

**Comment by huard** [comment]
Don't forget to log your time under the ETS-PAVICS project.

**Comment by Zeitsperre** [comment]
The HydroSHEDS 15s and 30s DEMs are now on CRIM infra (production server) under `/data/datasets/hydrosheds` and the HydroBASINS vectors are under `/data/geoserver/data/SHP/Hydrosheds`. The HdroSHEDS DEMs are in ArcInfo Binary Grid (.adr) format, readable with GDAL. The instance needs to be recrawled to integrate the new DEMs.

No error-correction in QGIS was performed on the vectors but (I'm hoping) everything should work fine. I've added a set of HydroBASINS files (hybas_ar_lev06_v1c and hybas_na_lev06_v1c) to the GeoServer instance for verification.

![screenshot_2018-06-20_15-03-25](https://user-images.githubusercontent.com/10819524/41679127-244df95e-749b-11e8-9f21-e4f8ae0839b3.png)

**Comment by huard** [comment]
I suggest we mark as verified when we show the delineation process ( #4 ) works.

**Comment by huard** [comment]
I don't think we need these on THREDDS at the moment. We could defer that to the maintenance phase next year if there is a demand for it.

**Comment by tomLandry** [comment]
How can we help here?
