### ISSUE TITLE
Emulate HMETS in Raven (16)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#10]

**Comment by richardarsenault** [comment]
Julie will integrate HMETS into RAVEN with the help of James Craig.

**Comment by huard** [comment]
@julemai Is the effort estimate reasonable (8 days) ? Could you please check Raven related issues to make sure that the values in parentheses roughly reflect the number of days of work needed to get them done. As I'm not familiar with Raven, the values I put are just guesses.

**Comment by julemai** [comment]
@huard I have a meeting with James Craig about this topic tomorrow. So, I will update you by tomorrow.

**Comment by julemai** [comment]
@huard The meeting with James was very fruitful. The implementations for HMETS are a bit more extensive as there is not a lot we can use out-of-the-box processes from RAVEN. The estimate might be a bit too optimistic. We will have a running version at our meeting in October. It might be not fully done but most parts.
