### ISSUE TITLE
PHASE II: Recode and compile the 4 hydrological models currently fixed in the Raven model setups

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#107]
### To do in maintenance phase for efficiency

The RAVEN model setups are currently fixed for 4 models (GR4JCN, HMETS, MOHYSE, HBV-EC). Unfortunately, calibration is taking much more time than we can allow due to repeated I/O calls. We should provide compiled versions of these models that are callable directly from Python in order to speedup the calibration times. 

This involves:

- [ ] Recoding the 4 hydrological models in C/Fortran/Other compilable language with interface to Pyhton

- [ ] Create new WPS services to calibrate with a fast python DDS algorithm (and/or others) that can efficiently calibrate the compiled models (no disk I/O)

- [ ] Replace the Fixed Ostrich calibration setups to allow calibrating the new Flexible Raven setup (see #106), including updating all WPS services

**Comment by julemai** [comment]
Before we recode all the models, we could just try to speed up Raven. :)

It is because the reading of NetCDF time series is not really fast. I am also not sure if you have switched Raven to the calibration mode (means that no output except hydrographs and Diagnostics is written).

**Comment by richardarsenault** [comment]
Yeah, we had tested that last time with GR4J where the matlab mex version calibrated 40X faster than Raven. Ideally we would want Raven to handle input/outputs bindings from memory but last time James seemed to say that it was going to be quite some work and did not seem like it was going to be doable in a reasonable amount of time? 

Of course if we can get that, then this is a moot point :)

**Comment by richardarsenault** [comment]
@julemai 
Hi! Do you know if there has been progress on the RAVEN-DDS development side? Thanks!

**Comment by richardarsenault** [comment]
I'll close this issue and open another with the Raven-DDS impementation.
