### ISSUE TITLE
Need to define classes for land-cover aggregation from Tiff

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#109]
## Description

Need to go from ~20 classes down to ~5 for regionalization.

**Comment by richardarsenault** [comment]
@Zeitsperre Is the dataset the NALCMS? With 19 classes? Depending on the discretization (There is another set with over 60 classes) I can provide a classification to agregate similar use classes.

**Comment by Zeitsperre** [comment]
@richardarsenault Yes, the raster we ended up going forward with is the CEC NALCMS (2010). From the metadata:
```
The following list describes the display of land cover classification in the .img file:
Value 1, Temperate or sub-polar needleleaf forest, RGB 0 0.24 0;
Value 2, Sub-polar taiga needleleaf forest, RGB 0.58 0.61 0.44;
Value 3, Tropical or sub-tropical broadleaf evergreen forest, RGB 0 0.39 0;
Value 4, Tropical or sub-tropical broadleaf deciduous forest, RGB 0.12 0.67 0.02;
Value 5, Temperate or sub-polar broadleaf deciduous forest, RGB 0.08 0.55 0.24;
Value 6,  Mixed forest, RGB 0.36 0.46 0.17;
Value 7,  Tropical or sub-tropical shrubland, RGB 0.7 0.62 0.18;
Value 8,  Temperate or sub-polar shrubland, RGB 0.7 0.54 0.2;
Value 9,  Tropical or sub-tropical grassland, RGB 0.91 0.86 0.37;
Value 10, Temperate or sub-polar grassland, RGB 0.88 0.81 0.54;
Value 11, Sub-polar or polar shrubland-lichen-moss, RGB 0.61 0.46 0.33;
Value 12, Sub-polar or polar grassland-lichen-moss, RGB 0.73 0.83 0.56;
Value 13, Sub-polar or polar barren-lichen-moss, RGB 0.25 0.54 0.45;
Value 14, Wetland, RGB 0.42 0.64 0.54;
Value 15, Cropland, RGB 0.9 0.68 0.4;
Value 16, Barren lands, RGB 0.66 0.67 0.68;
Value 17, Urban, RGB 0.86 0.13 0.15;
Value 18, Water, RGB 0.3 0.44 0.64;
Value 19, Snow and Ice, RGB 1 0.98 1.
```
If you can provide suggested groupings, I can go about creating a definition that can be referenced to reclassify pixels on-the-fly and then replace the category names within the JSON or GeoJSON outputs. I should have some time to put towards this in the next week.

**Comment by Zeitsperre** [comment]
We can also consider integrating the MODIS Annual Land Cover imagery (500m resolution) https://lpdaac.usgs.gov/products/mcd12q1v006/. After all, 2010 was a while ago now :sweat_smile:.

Classifications for those are in either 17 (IGBP) or 15 (UMD) categories. It probably wouldn't be too hard to integrate in the future. Ideally, a 2020 version of the CEC NALCMS should be available soon, but I have no idea if this is in the works.

**Comment by huard** [comment]
That would be for the maintenance phase.

**Comment by richardarsenault** [comment]
OK great. Here is a list of suggested groupings:

Group 1: Forest
Value 1, Temperate or sub-polar needleleaf forest, RGB 0 0.24 0;
Value 2, Sub-polar taiga needleleaf forest, RGB 0.58 0.61 0.44;
Value 3, Tropical or sub-tropical broadleaf evergreen forest, RGB 0 0.39 0;
Value 4, Tropical or sub-tropical broadleaf deciduous forest, RGB 0.12 0.67 0.02;
Value 5, Temperate or sub-polar broadleaf deciduous forest, RGB 0.08 0.55 0.24;
Value 6,  Mixed forest, RGB 0.36 0.46 0.17;

Group 2: Shrubs
Value 7,  Tropical or sub-tropical shrubland, RGB 0.7 0.62 0.18;
Value 8,  Temperate or sub-polar shrubland, RGB 0.7 0.54 0.2;
Value 11, Sub-polar or polar shrubland-lichen-moss, RGB 0.61 0.46 0.33;

Group 3: Grass (low vegetation)
Value 9,  Tropical or sub-tropical grassland, RGB 0.91 0.86 0.37;
Value 10, Temperate or sub-polar grassland, RGB 0.88 0.81 0.54;
Value 12, Sub-polar or polar grassland-lichen-moss, RGB 0.73 0.83 0.56;
Value 13, Sub-polar or polar barren-lichen-moss, RGB 0.25 0.54 0.45;
Value 16, Barren lands, RGB 0.66 0.67 0.68;

Group 4: Wetland
Value 14, Wetland, RGB 0.42 0.64 0.54;

Group 5: Crops
Value 15, Cropland, RGB 0.9 0.68 0.4;

Group 6 : Impervious/water
Value 17, Urban, RGB 0.86 0.13 0.15;
Value 18, Water, RGB 0.3 0.44 0.64;
Value 19, Snow and Ice, RGB 1 0.98 1.

I think that would make sense from a hydrological perspective.

**Comment by Zeitsperre** [comment]
Working on this today. I should have updates this afternoon.
