### ISSUE TITLE
Notebooks are returning NetCDF objects rather than Xarray objects

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#110]
## Description

Since last update, using the attribute resp.get(asObj=True) returns NetCDF4 objects instead of xarray on my machine. Tested in notebooks and in pure python script.

**Comment by richardarsenault** [comment]
@huard 
Could it be that the new converter tools in Birdy 0.6.0 are causing this? It used to return xarray objects but I am now getting just ordinary NetCDF objects.

**Comment by huard** [comment]
@richardarsenault Yes, correct. I did some refactoring and did not notice the "converter checker" did not find xarray anymore. Will fix rapidly.

**Comment by richardarsenault** [comment]
Works now with the current version, thanks
