### ISSUE TITLE
Filter features using Geoserver instead of Fiona in shape_selection

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#114]
## Description

It's possible to use WFS services to filter features for polygons containing a point. This would possibly be faster than downloading the features on the server and making the filter operation locally. 

See https://enterprise.arcgis.com/fr/server/10.3/publish-services/linux/communicating-with-a-wfs-service-in-a-web-browser.htm

**Comment by Zeitsperre** [comment]
@huard Short answer: Yes.

Longer answer: If we load the data into PostGIS database (converting it from shapefile to database via `ogr2ogr`) and the expose that on the GeoServer, we can access the service using SQLalchemy/GeoAlchemy using a really simple `FROM * SELECT table.feature WHERE ST_CONTAINS(<point location>, table.geom, ...);` query. 

I've set up PostGIS database accessing local data before. If I can figure out how best to setup and access the database locally without much finagling, we'll absolutely see a performance boost.
