### ISSUE TITLE
GIS notebooks

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#123]
## Description

Write flashy notebooks showcasing the GIS analytics of Raven.

**Comment by Zeitsperre** [comment]
Does this mean that the GIS functionalities we wanted in Raven are now complete?

**Comment by huard** [comment]
Yes, what's left would be UI components related to these functionalities. 
We might want to evaluate what could be done right from a notebook. If you have free cycle you might want to look into it.

**Comment by richardarsenault** [comment]
There is already a well-advanced notebook for GIS aspects in docs/sources/notebooks/delineation_workflow.ipynb

I have added some codes to extract lots of information, I'll push it later tonight.

**Comment by richardarsenault** [comment]
I have added a code I used to extract all GIS data in the regionalizationData branch, in tests/testdata/regionalization_data.
