### ISSUE TITLE
Host Canopex data on THREDDS (2)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#124]
## Description

- [x] Check Canopex metadata
- [x] Add to THREDDS

Related to #37

**Comment by richardarsenault** [comment]
@huard The file @Zeitsperre provided seems to be OK to add to THREDDS. I'd need a crash course on communicating with that dataset from our Notebooks to develop some workflows.

**Comment by huard** [comment]
Ok, please create a ticket with what you have in mind. 

This is probably a good occasion to implement URL subsetting. 

That is, you can pass an URL that includes a subsetting command, so for example, what would happen is: 
- using DAP url, read file metadata
- Find the index of the site of interest
- Construct the URL to access this site only
- Pass this URL to a RAVEN process expecting a netCDF resource
