### ISSUE TITLE
Allow exporting of the Raven setup files to the users

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#125]
Currently, users must build their Raven model files using the provided guidelines. This can sometimes be complex. This RAVEN package does the grunt work to be able to run and so it would be possible to use this service to generate Raven input files that can then be used to run the Raven model locally.

In essence, we would like to Export generated rv? files.

**Comment by huard** [comment]
Working on it. 
Should the output be a zip file storing the configuration files ?
How should it behave for multiple parameters and multiple models ? Do you want subdirectories inside the zip for each model run ?

**Comment by richardarsenault** [comment]
Good question. Should we limit this option to single model setups? If we want to go for the all-in-one approach, then yes I think we should have everything in separate zip files. However maybe the EXE should not be included in the package for the larger sets (i.e. more than one model setup/parameter set)? Or do we want to simply not put the model .exe at all?

**Comment by huard** [comment]
I was not planning to include the .exe anyway, as it would be 1. large, 2. client hardware dependent.

The question is really about the rv configuration file structure when there is more than one model run. We're constrained by WPS in having a single output file for all configuration files, the freedom we have is in what we put into that zip file and how it's organized.

**Comment by richardarsenault** [comment]
OK then yes, I think your idea of having nested zip files is the best way forward. Sounds good to me anyways. And good point for the exe being system dependent, didn't think of that.
