### ISSUE TITLE
Terrain analysis only seems to work with multi-polygon features

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#127]
Terrain analysis has been performed using wps_generic_terrain_analysis on the 5797 catchments. Only those that have more than 1 polygon (for example those that have an orphan pixel that is not joined to the main polygon) work. The others return errors:

 owslib.wps.WPSException : {'code': 'NoApplicableCode', 'locator': 'None', 'text': 'Process failed, please check server error log'}

And in the server error log:
2019-05-18 07:41:55,442] [WARNING] line=118 module=wps_generic_terrain_analysis CRS for /tmp/pywps_process_ptcvzq48/wcs_1bz1xa7l.tiff is not EPSG:6622. Reprojecting raster...
**2019-05-18 07:41:55,815] [ERROR] line=229 module=Process Process error: wps_generic_terrain_analysis.py._handler Line 140 'Polygon' object is not iterable**
2019-05-18 07:41:55,924] [INFO] line=271 module=Process Removing temporary working directory: /tmp/pywps_process_ptcvzq48
2019-05-18 07:41:56,707] [INFO] line=306 module=Service Request: execute
2019-05-18 07:41:56,782] [INFO] line=143 module=complexvalidator validating GeoJSON; Mode: 0
2019-05-18 07:41:56,960] [INFO] line=29 module=__init__ Processing mode: default

I think I can trick the system into working by adding a dummy polygon to each catchment, but we would need to fix this for future users.

I've added 2 test cases: Basin_1.shp works because it has a few polygons. Basin_10.shp does not work and has only 1 polygon. This holds true for the 5797 catchments in the database so I am pretty confident in this assessment, No idea how to tackle the problem though.
[Basin_1.zip](https://github.com/Ouranosinc/raven/files/3194715/Basin_1.zip)
[Basin_10.zip](https://github.com/Ouranosinc/raven/files/3194716/Basin_10.zip)

**Edit**: My workaround of adding an orphan pixel worked for a few catchments, now I am getting either the same error message, or this new one:

2019-05-18 23:50:29,884] [WARNING] line=118 module=wps_generic_terrain_analysis CRS for /tmp/pywps_process_upbojpog/wcs_cuxe3tom.tiff is not EPSG:6622. Reprojecting raster...
2019-05-18 23:50:30,479] [ERROR] line=229 module=Process Process error: wps_generic_terrain_analysis.py._handler Line 140 not enough values to unpack (expected 4, got 0)
2019-05-18 23:50:30,586] [INFO] line=271 module=Process Removing temporary working directory: /tmp/pywps_process_upbojpog

**Edit 2**: Upon further investigation, I have found that all catchments with latitude points below 40°N are failing. I assume the DEM/Raster does not cover the entirety of the USA?

**Comment by Zeitsperre** [comment]
@richardarsenault The DEM should be available for all of North America. The PAVICS instance also shows that the coverage is available, so I'm not sure how that's happening.

It's possible that I didn't write a case for simple polygons. I have limited time this week for raven, but I'll see if I can spend some time on this problem specifically.

**Comment by richardarsenault** [comment]
@Zeitsperre Hmmm is it possible that the slope DEM is not calculated beyond 40°N? the terrain_analysis is the only wps service that is not working. the shape_properties works, as does the NALCMS Land Cover. And in my dataset it is a perfect match between the 40°N limit and the code working or not. All above 40°N work, all others fail (about half-half on a 5797-basin dataset). Unless something else I don't see could be affecting this and giving these results?

**Comment by Zeitsperre** [comment]
The CRS should be also cover areas south of 40N, but in case that is indeed the issue, can you try running your analysis using `3978` or `102008`. These projections cover USA and Canada so anything dropping below 40N should be supported. Storage space for intermediary files shouldn't be an issue either, even with such a large number of features.

Also, the handling for polygon and multipolygon features should be fine. I don't imagine there being an issue for single feature shapefiles but I'll have to check in on that when I'm at the office.

**Comment by richardarsenault** [comment]
Oh yeah I hadn't thought of the projection.. I just checked and 6622 (Quebec Lambert) covers most of NA over 40.04°N, which would explain the problem!

**WGS84 bounds:
-141.01 40.04
-47.74 86.46**

Do you think the results will still be good if I change the projection? In any case, I've started the runs and it works!! So we can quality-check after but at least a basic DB will be ready.

Thanks for your help!

**Comment by Zeitsperre** [comment]
The quality depend on the purposes. I should try looking into a generic CRS for North America that we can use by default. I know for some calculations performed via PostGIS, the Great Circle distances are used, but these are really simplified. Worth looking further into.

**Comment by huard** [comment]
@richardarsenault Les liens vers les fichiers tests ne marchent pas pour moi.

**Comment by huard** [comment]
J'ai "guessé" d'où venait l'erreur dans fix-127. Probabilité de succès faible...
