### ISSUE TITLE
Add support for parallel multi-model analysis (8)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#13]
This would probably be a process calling other processes to benefit from parallelism and scalability. Not clear to me how that would work.

**Comment by richardarsenault** [comment]
For now, multi-model analysis should be performed in series, as it will be in simulation mode only (thus very fast with our models). We can paralellize the entire task to do multi-basins.

**Comment by richardarsenault** [comment]
Perhaps this would be called by Issue #14 to accelerate, but for now this would be limited to large-scale runs, not sure of the benefits with the faster models.
