### ISSUE TITLE
shape-selection improvements

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#139]
## Description

Things to improve with shape-selection process
- The name. The process is specific to HydroSheds, while the name is generic. 
- aggregate_upstream: depending on whether this is set to True/False, the output's type changes. Either make it a FeatureCollection or a Feature. 
- At the moment the level and lakes parameters are there but if we select anything but the default, an error is raised.

**Comment by Zeitsperre** [comment]
@huard Good to close?
