### ISSUE TITLE
Add support for multi-model uncertainty analysis (8)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#14]
Is this a process or a workflow ?

**Comment by tomLandry** [comment]
If you have the question "process or workflow", this might point to work conducted at OGC in the testbeds by CRIM and others. This might be an "application package" that is composed of a single-element workflow, or a process. Anyway, point is that is work in progress for the general process-workflow-app continuum.

**Comment by richardarsenault** [comment]
Excellent. This should be relatively straightforward and could be considered a substep of the multi-model analysis issue

**Comment by richardarsenault** [comment]
WPS takes a list of hydrological models and a list of climate data series, and generates a series of hydrographs.

Inputs:
List of hydrological models (List of Strings, i.e. {'HMETS','MOHYSE','GR4J'})
List of climate data (List of strings, perhaps OpenDAP NetCDF links that will be used to drive the models)
Parameters for each of the models, txt file format?
Other data required to run the models (latitude, day of year dates, area, etc.).

Outputs: A matrix of size nDays x [nModels x nClimates], with a header indicating the hydro/climate model combo.

**Comment by huard** [comment]
figure showing enveloppe
