### ISSUE TITLE
fix dockerfile

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#141]
## Description

The Dockerfile should run `make install` to download and compile the RAVEN hydrological model and OSTRICH. This creates binary executables that are essential to the services. 

Is it possible to run the test suite when the docker image is built and report errors ?

**Comment by huard** [comment]
Should we add in the `__init__.py` a check to make sure the binary is there ?

**Comment by tlvu** [comment]
> Should we add in the `__init__.py` a check to make sure the raven and ostrich binaries are there ?

This is a great idea.

> Is it possible to run the test suite when the docker image is built and report errors ?

We can add extra steps in the Dockerfile to run the test suite.  Is the test suite able to run outside the checkout dir to test the "real world"?

**Comment by huard** [comment]
Will take care of the init then pass you the puck for the docker file.

Not sure I understand what you mean. We just want to make sure that the docker build is functional. Whether it is well integrated in the platform will be the job of the notebook tests.

**Comment by huard** [comment]
The init checks are already there... I don't understand why they didn't raise an error.

**Comment by huard** [comment]
Argh ! Got it.

**Comment by tlvu** [comment]
> Not sure I understand what you mean. We just want to make sure that the docker build is functional. Whether it is well integrated in the platform will be the job of the notebook tests.

I was thinking instead of writing new tests, can we just reuse some or most of the unit tests suite but running at the end of the docker build.  But those unit tests must be able to run from the installed binaries, not from the code inside the checkout.

Just an idea ... might not work.

What's are the minimal tests to confirm  the docker build is functional?

**Comment by huard** [comment]
If `pytest tests/` runs with no error, then everything is functional. It means the binaries were installed correctly. But we probably don't want to have to run those tests every time we launch the container, just when we build.

**Comment by huard** [comment]
Note that we'd need to install pytest and pytest-dependency before running the test suite.
