### ISSUE TITLE
Configure magpie

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#143]
## Description

raven roule maintenant sur boreas, mais je pense qu'il faut accorder les permissions sur magpie pour que ça marche.

**Comment by tlvu** [comment]
C'est fait ... désolé j'ai oublié ce petit détail encore manuel ... argggggggghhhh ... faudra qu'on puisse aussi déployer la config de magpie avec magpie.  Faire la config à la main dans le Web UI ne scalera pas.
