### ISSUE TITLE
HMETS OSTRICH calibration does not return same NSE as an identical run using the optimized parameters.

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#145]
Test can be performed in notebook: Running_OSTRICH_hmets

**Comment by richardarsenault** [comment]
@julemai @huard : This can also be spotted in the test_emulators.py test, line 359 in HMETS_OST. It has not been resolved.

**Comment by julemai** [comment]
I can have a look tomorrow. Which branch are you working in?

**Comment by richardarsenault** [comment]
You can look at branch fix-222, test_emulators.py in HMETS_OST. Thanks!

**Comment by julemai** [comment]
Just a quick update. I am looking into this since quite a while now. My best guess is that the derived parameters are not correctly handled.

I (again) don't know how to access the actual run folders on my Mac when a test is failing. Any idea how I do that. I run `make test` in my terminal.

**Comment by julemai** [comment]
One thing I already found is that in `emulators.py` the following need to be adjusted:
```
        self.rvd['SUM_MELT_FACTOR'] = self.rvp.params.MAX_MELT_FACTOR   
        self.rvd['SUM_SNOW_SWI'] = self.rvp.params.SNOW_SWI_MAX     
```
instead of using:
```
        self.rvd['SUM_MELT_FACTOR'] = self.rvp.params.MIN_MELT_FACTOR + self.rvp.params.MAX_MELT_FACTOR 
        self.rvd['SUM_SNOW_SWI'] = self.rvp.params.SNOW_SWI_MIN + self.rvp.params.SNOW_SWI_MAX 
```   
because some derived parameters are already derived in `model.optimized_parameters` while others aren't.

**Comment by julemai** [comment]
The `calibrated_params` of MOHYSE does not contain the 2 calibrated HRU values... So, the test for MOHYSE fails.

**Comment by julemai** [comment]
All tests except one are now working. :) 

@huard : The error I am getting for `tests/test_emulators.py::TestMOHYSE_OST::test_simple` is the following:
```
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_emulators.py", line 462, in test_simple
    params=model.calibrated_params
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/base.py", line 417, in __call__
    procs = self.run(ts, overwrite, **kwds)
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/base.py", line 410, in run
    cmd = self.setup_model_run(tuple(map(Path, ts)))
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/base.py", line 311, in setup_model_run
    self.derived_parameters()
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/emulators.py", line 68, in derived_parameters
    self.rvd['par_rezi_x10'] = 1.0 / self.rvh.hrus.par_x10
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```
This is due to the fact that the two calibrated HRU values (`para_x09` and `para_x10`) are not part of `params=model.calibrated_params`. I have no idea how to fix this. I've made all my fixes in `fix-222`.

**Comment by huard** [comment]
On it.

**Comment by huard** [comment]
Done.

**Comment by julemai** [comment]
Some other MOHYSE related tests are now failing. I can look into this if you want @huard.

**Comment by huard** [comment]
Darn, I forgot those. It's probably just a matter of removing references in the test files to hrus and appending the hru parameters at the end of the params.

**Comment by julemai** [comment]
Yeah, all three complain about the same:
```
Traceback (most recent call last):
  File "/Users/j6mai/miniconda3/envs/raven/lib/python3.6/site-packages/pywps/app/Process.py", line 227, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/Users/j6mai/Documents/GitHub/raven/raven/processes/wps_raven.py", line 74, in _handler
    data = self.tuple_inputs[name](*arr)
TypeError: __new__() missing 2 required positional arguments: 'par_x09' and 'par_x10'
```

**Comment by julemai** [comment]
Hang on! I think I fixed all of them...

**Comment by julemai** [comment]
Done. All tests pass.
