### ISSUE TITLE
Automate doc build on travis

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#148]
## Description

The readthedocs build is broken at the moment because the install is too large. 
We could use travis-ci to build the docs and push to github pages. 

See https://drdoctr.github.io/

- [ ] Add doc building to `.travis.yml` Py3.6 build
- [ ] Can we have the docs for every branch we push ? https://drdoctr.github.io/recipes.html#recipes
- [ ] Modify the canarie-api link to link to github.io

**Comment by tlvu** [comment]
What installs are required that is too large?  I am not familiar with readthedocs but can we provide it like a docker image with everything needed already installed so there are no installs to do and on top of that this allows us to lock down on all recursive versions of the installs (aka reproducible environment)?

**Comment by Zeitsperre** [comment]
The reason that the build is failing is because of the memory requirements needed to install the conda environment. From the build statuses:
```
conda env create --quiet --name stable --file environment.yml
Collecting package metadata: ...working... done
Solving environment: ...working... Killed

Command killed due to excessive memory consumption
```
Is it really possible to send RtD a docker image that it can run directly from?

**Comment by tlvu** [comment]
Like I said, I have no experience with readthedocs so what I said about docker image is pure speculation.  However, we are probably not the only one needing a large install ... I wonder what are readthedocs recommended best practice for similar case.

**Comment by huard** [comment]
Conda support is fairly new in RtD, and I've heard nothing about docker support.

**Comment by tlvu** [comment]
https://docs.readthedocs.io/en/stable/builds.html
"The build process is executed inside Docker containers, by default the image used is readthedocs/build:latest, but you can change that using a Configuration File."

If using our own docker image does not work, another way out is 
"Every documentation build has limited resources. Our current build limits are:

    15 minutes of CPU
    1GB of RAM memory

We can increase build limits on a per-project basis, sending an email to support@readthedocs.org providing a good reason why your documentation needs more resources.
"

**Comment by tlvu** [comment]
ReadTheDocs team is working on a feature to allow upload of pre-build docs https://github.com/rtfd/readthedocs.org/issues/1083

**Comment by huard** [comment]
I don't see a related PR. I would not hold my breath for this feature.

**Comment by tlvu** [comment]
ReadTheDocs might be willing to increase our memory limit, see discussion in https://github.com/rtfd/readthedocs.org/issues/5847#issuecomment-505651860

**Comment by huard** [comment]
Ok, but I'm still not sure how this is better than building the docs on Travis.

**Comment by tlvu** [comment]
It's not Travis, it's hosting on Github that I prefer not to.  I noticed many weird multiples glitches with Github since Microsoft acquired it.  I've shown some of the glitches to @Zeitsperre.  I'd rather us not depend on more Github services.  Is there somewhere else we can host our docs?

**Comment by huard** [comment]
Are these glitches specifically related to gh-pages ? We've been using this for pavics-sdi for two years now without issue. 
If it's not broken, don't fix it.

**Comment by tlvu** [comment]
Github glitches not related to gh-pages.  The guys at RTD is giving me some leads on how to generate docs without installing dependencies (so no memory problems anymore), see https://github.com/rtfd/readthedocs.org/issues/5847#issuecomment-505960920.  So I'd like to give it a shot before giving up.

**Comment by huard** [comment]
Understood, but autoapi won't work for us.

**Comment by Zeitsperre** [comment]
@tlvu Let's start back on this when you have a minute. Let me know when you're free.

**Comment by huard** [comment]
One problem I have at the moment is that the platform documentation requires installing multiple packages that are often difficult to get to work together. I would like the pavics-sdi documentation to be able to pull from the individual package documentation, as I think this would simplify the build. 

1. Automate build for individual birds with travis, push to gh-pages
2. Set-up intersphinx in pavics-sdi to pull content from the individual birds.

**Comment by tlvu** [comment]
WIP branch: https://github.com/Ouranosinc/raven/tree/fix-rtd-build-with-smaller-env-yml

RTD test doc build: https://pavics-raven.readthedocs.io/en/fix-rtd-build-with-smaller-env-yml/
Sample Build log: https://readthedocs.org/api/v2/build/9479705.txt

Solved the memory limit bursting problem, just autodoc left to solve.

Sample error in build log above breaking autodoc:
```
WARNING: autodoc: failed to import process u'processes.RavenProcess' from module u'raven'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-raven/conda/fix-rtd-build-with-smaller-env-yml/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-raven/checkouts/fix-rtd-build-with-smaller-env-yml/raven/__init__.py", line 5, in <module>
    from .wsgi import application
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-raven/checkouts/fix-rtd-build-with-smaller-env-yml/raven/wsgi.py", line 4, in <module>
    from .processes import processes
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-raven/checkouts/fix-rtd-build-with-smaller-env-yml/raven/processes/__init__.py", line 1, in <module>
    from .wps_raven import RavenProcess
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-raven/checkouts/fix-rtd-build-with-smaller-env-yml/raven/processes/wps_raven.py", line 7, in <module>
    from raven.models import Raven
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-raven/checkouts/fix-rtd-build-with-smaller-env-yml/raven/models/__init__.py", line 3, in <module>
    from .base import Raven, Ostrich
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-raven/checkouts/fix-rtd-build-with-smaller-env-yml/raven/models/base.py", line 32, in <module>
    from .rv import RVFile, RV, RVI, isinstance_namedtuple, Ost
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-raven/checkouts/fix-rtd-build-with-smaller-env-yml/raven/models/rv.py", line 53
    raise ValueError(msg) from e
                             ^
SyntaxError: invalid syntax
```
