### ISSUE TITLE
Let users calibrate model with metropolishasting

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#159]
## Description

I'd like to try different calibration algorithms, but it doesn't work out of the box at the moment. 
In particular, we're interested in the MCMC sampler. It seems it only works with the WSSE metric. Would that be just RMSE squared ? How do we compute this in Ostrich ?

At the moment there is no connection in the python wrapper between the OST configuration and the raven configuration, everything is pretty much hard-coded and fragile (the CostFunction is defined from a tied variable checking the diagnostic's 3rd column). 

@julemai Do you have some tips on this ?

**Comment by richardarsenault** [comment]
@huard can we try GLUE (I know) because in the Ostrich Manual it seems that it can handle other metrics while MCMC only handles WSSE.

**Comment by huard** [comment]
GLUE seems to work better, but `save_best.sh` does not seem to be called, so there is nothing in the `final` directory.

**Comment by richardarsenault** [comment]
@julemai @huard is this any easier to implement now with the updates to ostrich and raven?

**Comment by richardarsenault** [comment]
Ravenpy will make this possible for users if they import required packages. Out of scope for ravenwps.
