### ISSUE TITLE
Provide more RAVEN model configurations

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#169]
As of now, only 4 Raven model configurations are possible: HMETS, GR4JCN, MOHYSE and HBV-EC. Ideally we would want to add maybe 6 other configurations for various reliefs and climates (i.e. good in plains, in mountains, coastal, arid, etc.)

This would be done with the expertise and knowledge of the raven configs that James Craig had proposed.

**Comment by huard** [comment]
PRs submitted to RavenPy. Closing this here.
