### ISSUE TITLE
Integrate the Canadian HydroLakes routing model for RAVEN distributed modelling

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#170]
Waterloo (Bryan and Ming) have developed a routing model that takes into consideration the topography and lakes in flow routing, which allows building a raven distributed modelling file. 

Right now, the tool uses ArcGIS for some catchment delineation and slope/channel burning calculations, however it seems this can be replaced by simple calls to GDAL. 

The aim is to provide an easy method to build a distributed raven model based on all the information we can get at the HydroBasins Level 12 delineations.

Perhaps @Zeitsperre and Ming can work together on this.

**Comment by Zeitsperre** [comment]
@richardarsenault Sounds good. Is there a PR/branch/gist somewhere with the core algorithms laid out? Seeing as Raven is relying on Rasterio and Fiona, writing calls to GDAL using a bit of a step backwards. I've written a few generic tools using them into the utilities that we can also probably leverage. I just need a look at what needs replacing.

**Comment by julemai** [comment]
@Zeitsperre We don't insist on GDAL calls. It is only that the toolbox is using ArcGIS functions right now and they (supposedly) should be replaced for this project. The codes are not yet available. I have to talk to Bryan and Ming but I am assuming that they want to publish this first.

**Comment by Zeitsperre** [comment]
Depending on the type of functions being called, there are either drop-in replacements using QGIS or if the functions are generic enough (intersections, differences, buffers, etc.) they can be replaced by Rasterio, Fiona, or frameworks like GeoPandas. Keep me in the loop!

**Comment by julemai** [comment]
@dustming has revised his routing code such that it does not include any ArcGIS functions anymore- not even for the delineation. @huard, Ming would need some advise for the next steps to integrate this into PAVICS. He provided an example setup [here](https://github.com/Ouranosinc/raven/wiki/Technical-Notes#routing-toolbox). What would be a good next step?

**Comment by huard** [comment]
@dustming @julemai 
I *think* it would look something like this... 

- In `utilities/` add the toolbox code. It should return strings with the content to be embedded in rv files.
- Include in the RV templates (raven/models) tags for the content generated by the toolbox, for example {model_channel}. 
- Update rv.py to reflect the presence of these new tags.

Usage
- Use the toolbox functions to create the configuration strings
- Pass those strings when calling the model.

**Comment by huard** [comment]
I'll close this as I think we have the setup in RavenPy to create configuration files. Remaining tasks are getting the gis layers from the server, and the embedding the semi-distributed config files in the emulators.
