### ISSUE TITLE
Provide workflow notebooks for a suite of tasks

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#173]
Provide a suite of hydrological modelling notebooks to perform tasks, and document them clearly as to be modifiable by users with little experience. Ensure that the results obtained are realistic and that the results can be interpreted. Provide guidelines on the use of various methods.

**Comment by huard** [comment]
@richardarsenault Is this covered by our nb ?

**Comment by richardarsenault** [comment]
Yes, that was the plan!
