### ISSUE TITLE
Add support for simulation in ungauged catchments (8)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#18]
This can be done by running models for nearby calibrated catchments and averaging the outputs. 
TODO: Clarify method and split in smaller issues.

**Comment by richardarsenault** [comment]
I will have Jean-Luc do this task. We'll need to upload a dataset of parameters for pre-compiled models and predefined catchments. The algorithm itself has been built in Matlab, now we will convert it to Python.

Steps:
1- Push a series of catchments to the server (including contours and observed streamflow)
2- Calibrate the 3 main hydro models on each site using the RAVEN framework once it's functional, and using observed climate date (we can provide reference climate data if need be, i.e. gridded NLWIS data for now)
3- Convert Matlab Code to Python for the regionalization strategy
4- Implement the WPS to automate the process given an input catchment contour (i.e. select 5 closest calibrated watersheds with the model chosen by the user, run the hydromodel on the ungauged site using the parameter sets from these 5 catchments and the gridded climate data at that site, then average the 5 outputs).

**Comment by huard** [comment]
Could this be relevant: doi:10.5194/hess-15-3591-2011 ?

**Comment by richardarsenault** [comment]
It is actually a relevant topic in theory, but is difficult to apply in practice. I did my PhD partly on this, the problem is that the regression relationships between model parameters and exogenous characteristics are very difficult to model and not very robust. So it's not really an applicable method... yet.

**Comment by huard** [comment]
Ok, I got carried away. We're looking to implement methods people are familiar with, not do research.

**Comment by richardarsenault** [comment]
Maybe in maintenance phase! It's a good idea though, just not mature enough.

**Comment by richardarsenault** [comment]
@marteljeanluc 
@marteljeanluc 

This will be accomplished in 3 phases:

(1) Pre-calibrate HMETS, GR4JCN and MOHYSE on CANOPEX database in Canada and USGS database in USA. This will give a set of parameters for use in the regionalization method application.

(2) Implement the Spatial proximity regionalization method (with inverse-weighted donor averaging). Need the climate data for the ungauged catchment, latitude, longitude and area, as well as any other info to run the model at the ungauged site. The algorithm finds the parameter sets from the closest catchments that have a reasonable calibration NSE (>0.7 usually, can be reduced to 0.6) and runs the hydro model on the ungauged site using these parameters. We can then use 1-10 "donor" catchment parameter sets to average out the hydrographs.

(3) Expand on this by adding physical descriptors to the datasets (can use PAVICS GIS WPS for this...) and implement the physical similarity regionalization variants.
