### ISSUE TITLE
User accounts on JupyterLab 

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#184]
## Description

Use same credentials as for Magpie, so that once in Jupyter notebooks, there is an access to processes and data.

**Comment by tlvu** [comment]
Depends on https://github.com/Ouranosinc/Magpie/issues/174.  Once that Magpie issue is resolve, still have to somehow find a way to propagate/expose that authentication token from JupyterHub to all the notebooks (is this supported in the security model of JupyterHub to expose authentication token).

Also having JupyterHub authentication integration with Magpie will benefits all the processes, not just Raven so I just wonder why is this issue open in Raven?

**Comment by huard** [comment]
Because it was part of our original proposal, but comfortable with moving it.

**Comment by tlvu** [comment]
We can leave this issue here.  I was just wondering.  Thanks.

**Comment by tlvu** [comment]
JupyterHub authentication using Magpie is done in PR https://github.com/bird-house/birdhouse-deploy/pull/16.

Just missing the integration when running notebooks.
