### ISSUE TITLE
Update to latest cookie-cutter

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#187]
Work on tools to help with this: https://github.com/bird-house/cookiecutter-birdhouse/pull/79
This is currently being done for Finch. I suggest we wait until it's done to Finch before doing it to Raven.

**Comment by Zeitsperre** [comment]
Putting these here for (near) future reference:
* https://timothycrosley.github.io/cruft/
* https://scaraplate.readthedocs.io/
