### ISSUE TITLE
Select land-use raster database (2)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#2]

**Comment by tomLandry** [comment]
Unsure if perfectly related, but a lot of coordination made by Nils on land degradation with the http://trends.earth/docs/en/ project. Forwarding email to you right now.

**Comment by richardarsenault** [comment]
There is a free-to-use Land-Cover raster available from the Land Cover Institute, it covers the entirety of North America at a 30km resolution:

http://www.cec.org/tools-and-resources/map-files/land-cover-2010-landsat-30m

**Comment by Zeitsperre** [comment]
We're already using CEC for a few other layers within PAVICS. This is easily integrable. There are finer resolution products available though. for instance, I mentioned MODIS on another issue.

Which spatial scale/extent are we most interested in?

**Comment by richardarsenault** [comment]
I was going to say, I think 30m is way better than what we need, we can even reduce the resolution some to save some space/computing time.

**Comment by Zeitsperre** [comment]
This is being followed up on in #3
