### ISSUE TITLE
WPS for graphical representation of model fit (2)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#20]

**Comment by richardarsenault** [comment]
Inputs: 
- Qobs and Qsim vectors, same length, including timestamps.
- Option for desired plot type (integer 1-3 for now)
- Filename for output
- Flag for DisplayStats (on/off) to display KGE/NSE/Bias/RMSE

Output: 
Option (1) : Plot of Qsim vs Qobs over the entire time-series
Option (2) : Plot of interannual mean hydrographs of Qobs and Qsim
Option (3) : Same as 2 but with entire variability including mean hydrograph Qsim and Qobs (Envelope style)
