### ISSUE TITLE
Add time to time units to CANOPEX data

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#205]
## Description

Raven needs time units in the `days since 1950-01-01`. 

We need to do 
```
# Add precision on time format for Raven
D = nc.Dataset(path, mode="a")
D.variables["time"].units += " 00:00:00"
D.close()
```
to `Watersheds_5797_cfcompliant.nc`.

**Comment by Zeitsperre** [comment]
@huard Am I correct in assuming that the original can be overwritten/destroyed?

**Comment by huard** [comment]
I would say *modified in place*.

**Comment by Zeitsperre** [comment]
I suppose that's a fine way of saying it as well. Certainly nicer-sounding.

In any case, the _modified_ file is now available.
