### ISSUE TITLE
Load CANOPEX shapefile to GeoServer

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#206]
## Description

Store CANOPEX shapefile to GeoServer.

**Comment by Zeitsperre** [comment]
@huard our prod server or testing server? both?

**Comment by huard** [comment]
prod

**Comment by Zeitsperre** [comment]
Done. The name of the layer on the WFS is `public:CANOPEX_5797_basinBoundaries`.

**Comment by huard** [comment]
Thanks ! I've got something else for you ; )

**Comment by Zeitsperre** [comment]
Hit me. I'm game : )
