### ISSUE TITLE
Get Canopex watershed from lat-lon

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#208]
## Description

There is a canopex notebook that fetches an abritrary watershed in the netCDF and runs Raven with it. We want to be able to specify a lat-lon, identify the watershed it belongs using the shapefile hosted on GeoServer, then get the associated series from the netCDF.

**Comment by Zeitsperre** [comment]
Sounds like a I can piggy-back on some existing notebooks to get this moving. What's the level of urgency on this?

**Comment by huard** [comment]
No urgency.

**Comment by Zeitsperre** [comment]
Okay. I'll keep it in my to-do list for now. Earliest I can tackle this would be later next week.

**Comment by richardarsenault** [comment]
@Zeitsperre @huard I think this can be removed and replaced with something much better, aka an intake-catalog. This would allow filtering for names and other features, and also bypasses the issue of nested basins where a lat-long coordinate could belong in 1, 2 or even 3 basins in the CANOPEX database.

I have no idea how to build an intake catalog but maybe we could piggyback off of what has been done for ERA5? And while we're at it, we could replace it with the HYSETS database that contains 14k catchments, including those from CANOPEX but more up-to-date.
