### ISSUE TITLE
WPS for model parameter uncertainty (4)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#21]

**Comment by richardarsenault** [comment]
If I understood correctly, OSTRICH provides this functionality? @julemai?

**Comment by julemai** [comment]
Yes, OSTRICH has an MCMC implementation in there. I don’t have experience with it in Ostrich. But I have a quote some experience with MCMC codes.

I’m 100% sure that Shawn would implement features we require if not already there.

**Comment by julemai** [comment]
Yay!! 
Any time!

**Comment by richardarsenault** [comment]
@huard @julemai 
Here are 2 packages that Julie has made available and that could be relatively easy to implement in PAVICS for parameter uncertainty and sensitivity:

Efficient Elementary Effects (EEE): https://github.com/julemai/EEE
Model Variable Augmentation (MVA): https://github.com/julemai/MVA

Thanks Julie!

**Comment by richardarsenault** [comment]
@julemai Is this somethig that we could implement relatively fast? If the method is in PAVICS I can relatively easily wrap it in a WPS and build the test suite.

**Comment by julemai** [comment]
It is already in PAVICS. I just don't understand how it works. And PAVICS should have to deal with this but RAVEN needs to. Shouldn't take too long. I just need a fresh mind and a coffee next to me.

**Comment by richardarsenault** [comment]
OK! If you point me to the location and inputs required I can also give it a shot.

**Comment by richardarsenault** [comment]
For example, do you absolutely need it to be an ascii file or could we pass the parameters and their ranges and variance as inputs to the function?

**Comment by richardarsenault** [comment]
Not convinced we should do a WPS for this. It should be a RavenPy item that uses functionalities in OSTRICH or a standalone function in RavenPy. thoughts @huard ?
