### ISSUE TITLE
Improve error handling for RAVEN and OSTRICH processes

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#210]
RAVEN and OSTRICH often indicate why an error happens in their respective log files. However, a user using a notebook through the production server does not have access to those logs. Ideally we can catch errors, parse the logs and return the error message to the user when that situation happens. That way users can correct their error/data instead of being stuck in limbo wondering why the process failed with the generic message "OWS exception...".

**Comment by huard** [comment]
Partially fixed. @cjauvin your solution should also be applied to other processes calling Raven. 
- wps_climatology
- wps_regionalization
