### ISSUE TITLE
Add NcML capability to some climate model data 

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#211]
Right now, the climate data must be called file by file, year by year, to create a multi-year time series. It would be great to quickly have access to 1 or 2 models using the NcML method as was done for ERA5 and NRCAN, so we can test full process integration including running a model with post-processed climate data to see the impacts of climate change. 

Ideally, the model/data should have both the future and reference periods. It can be only one RCP for now, it's just to setup the templates/models/workflows.

**Comment by tlogan2000** [comment]
Should be no problem 
Questions : 

- Are we wanting bias-corrected data? 

- Do we have a spatial domain needed for Raven?  Can we limit to Quebec / Eastern Canada ?

**Comment by richardarsenault** [comment]
I think the data should not be bias corrected, but instead we should offer bias correction methods to process the raw data.

For the regional aspect, Ideally North America (CAN/USA) as we will have users from the US as well. Are the data on THREDDS already subsetted to Quebec/Canada? if yes then for now we'll have to go with that I guess, if not I'd simply link the existing files?
