### ISSUE TITLE
Add nearest-neighbor method to netcdf subsetting

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#212]
One problem we face is that of small catchments whose polygons fall between climate model grid points. Our current codes take the average of all grid points within a catchment boundary as the climate data time series. This will fail for catchments with 0 points (return empty array). We need to catch this and revert to a plan B, either the average of the 4 bounding points (4 closest points to the center essentially) or simply take the nearest neighbor, perhaps with a warning message that this is what has been done.

**Comment by huard** [comment]
For nearest neighbour, you could use finch.subset_gridpoint. 
For averaging over an area, this is still a WIP.

**Comment by richardarsenault** [comment]
OK so for now we can use the local "salem" roi process for larger catchments, and revert to finch.subset_gridpoint if there are no points. Make sense?

**Comment by huard** [comment]
Yes, but working on a flyingpigeon process to return the average over a shapefile, which I think will be robust to the situation you're pointing out.

**Comment by richardarsenault** [comment]
Yes exactly, good. Keep me posted when that process is implemented so we can switch from salem to FP.

**Comment by Zeitsperre** [comment]
@richardarsenault I would be careful with building too much based off of `salem`. It doesn't seem to receive too many updates and the dependencies are quit out of date (to the point that it doesn't jive with `xclim` anymore). Would you be open to different tools?

**Comment by richardarsenault** [comment]
Yes absolutely, actually I think the idea is that the subsetting will eventually be part of Finch? so that would basically supersede Salem

**Comment by tlvu** [comment]
> I would be careful with building too much based off of `salem`. It doesn't seem to receive too many updates and the dependencies are quite out of date (to the point that it doesn't jive with `xclim` anymore)

On the Jupyter env, `salem` has forced pinning much older version of `pandas` and `geopandas` https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/blob/0ffbd16b334e6628a19befd3c380c67b873e96eb/docker/environment.yml#L20-L23

**Comment by richardarsenault** [comment]
I have zero attachment to Salem, only to do the demo I needed something and it was the first I could get to work. If we can replace it by something more modern I'd be more than happy!

**Comment by richardarsenault** [comment]
Is this something that we can now do in the refactored Xclim?

**Comment by Zeitsperre** [comment]
@richardarsenault Actually, once the next version comes out, this won't be possible out of the box for xclim. The subsetting libraries are being migrated to another project (https://github.com/roocs/clisops/) where they will need to be loaded from. It will functionally be the same with some minor changes to the function calls. Hopefully the transition work for Raven won't be too complicated.

**Comment by huard** [comment]
I think this is now offered though Finch.
