### ISSUE TITLE
Add climate/streamflow netcdf checker

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#213]
The idea is that users can submit their own netcdf files with streamflow and/or climate data to run RAVEN and OSTRICH. However, the user should be able to call a WPS that will check the files to ensure that all data, units, time, variables, etc. are present and pass minimal quality checks. We could depend on that to (1) be a first source of conflict resolution for the user and (2) a simple method for us to add constraints/checks to the data as we find more problems with time without breaking the workflows.

**Comment by huard** [comment]
This would be specific to Raven ? Like, would this file be ok to run raven with ?

**Comment by richardarsenault** [comment]
Yes, for RAVEN, and maybe we could also have them separate like one process to verify if a nc file has OK streamflow data and another to see if met data is OK. That way a user could either submit different files for each process, or the same file to both processes (if Qobs and Meteo are in the same file). Then we could also use it to check for problems for analysis and distributions (detect problems like negative Qobs and things like that). But yes, ultimately the idea is to make sure the data will not cause problems in the modeling chain, and since most things use RAVEN then that is the core of the reflection.

**Comment by Zeitsperre** [comment]
Does https://github.com/cedadev/cf-checker evaluate hydrological parameters? I imagine it does.

**Comment by huard** [comment]
@Zeitsperre So there would be two part to this: 
1. Generic feedback on CF-compliance (could be existing cf-checker)
2. Raven specific-checks (checks that required variables are present)

So could start with adding https://github.com/bird-house/hummingbird/blob/master/hummingbird/processes/wps_hdh_cfchecker.py to raven and write a hook into it for us to add custom checks.

**Comment by Zeitsperre** [comment]
@huard Thanks for the clarification. Are you saying I should port that process to Raven or is there a hummingbird instance somewhere on prod that we can leverage?

**Comment by huard** [comment]
I'm not sure. I think hummingbird is running already in prod. So we probably don't want to duplicate that. I think we need to clarify expectations for this functionality before anything else.

**Comment by richardarsenault** [comment]
Closing because error messages are now passed with RavenPy.
