### ISSUE TITLE
ERA5 precipitation seems off in Notebooks

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#215]
Precipitation is extremely small in ERA5, with streamflow values essentially always tapering off to 0. Linear_transform has been set correctly, perhaps a problem with the hourly-->daily transform? Is precip being summed or averaged?

**Comment by Zeitsperre** [comment]
I know that with ERA5-land, precipitation is summed over hours and reset back to zero after 12 AM every day. This isn't the case for ERA5 precipitation. For more info: https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation

**Comment by Zeitsperre** [comment]
On the point of instantaneous or accumulated variables: https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation#ERA5:datadocumentation-Meanratesandaccumulations

**Comment by richardarsenault** [comment]
Thanks, I see that ERA5 has hourly precip that must be summed, but I am wondering if that is the way Raven handles hourly to daily precip because the streamflow values are way too low with ERA5 vs the others, like an order of magnitude or more lower. @julemai  any thoughts?

**Comment by julemai** [comment]
I am guessing ERA is in UTC time. Is there a time shift used for the NetCDF variables? And maybe a unit conversion? Raven does take in subdaily inputs and automatically aggregates them to the simulation time step. 

I could have a look tomorrow. Could you direct me to the specific notebook and outputs that are different?

**Comment by richardarsenault** [comment]
Yes I am pretty sure we use the time shift for ERA5. Actually I was wondering how Raven agregates precipitation, for example ERA5 precipitation is cumulative over 24h (so it's a 24-step cumsum function that resets to 0 each midnight) and ERA5 is actual precip per hour. So I am guessing one of the two will crash if Raven doesn't know which it is being fed!

Problem with notebooks is that the ones used to compare ERA5 and NRCAN were updated and/or a dependency was updated and now they're not working anymore, but there's an issue open for that. I'll try and setup another independent experiment in the meantime to test this.

**Comment by julemai** [comment]
Raven has an option to deaccumulate forcings but it would expect that it accumulates for the whole time series and not only from midnight to midnight.

**Comment by julemai** [comment]
Let me know when there is a branch I can checkout and look into.

**Comment by julemai** [comment]
I am getting closer to this. I will likely dig deeper into this tomorrow. I might just properly implement `add_offset` and `scale_factor` into Raven. It is definitely a missing feature.

**Comment by julemai** [comment]
Fixed! 

`rv.py`:

```
return ":LinearTransform {:.15f} {:.15f}".format(slope * sf, offset * slope + intercept)
```
instead of
```
return ":LinearTransform {:g} {:g}".format(slope * sf, offset * slope + intercept)
```
is doing the magic

**Comment by huard** [comment]
Good catch !
