### ISSUE TITLE
NcML for climate simulation 

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#216]
## Description

NcML for a historical and future climate model simulations.

**Comment by huard** [comment]
See https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/catalog/datasets/simulations/cmip5/atmos/catalog.html?dataset=datasets/simulations/cmip5/atmos/day_MPI-ESM-LR_historical.ncml

@richardarsenault please confirm this is what you were looking for. 
Future simulation coming up.

**Comment by richardarsenault** [comment]
@huard yes, that EXACTLY. It's perfect, thanks. Even includes 3 members, which is even better. Can't wait to get the future one and a Bias correction method :)

**Comment by huard** [comment]
We'll close when the future simulation is available.

**Comment by Zeitsperre** [comment]
Ah, good point. My bad!

**Comment by huard** [comment]
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/catalog/datasets/simulations/cmip5/atmos/catalog.html
