### ISSUE TITLE
ReadTheDocs builds are failling

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/raven#220]
See: https://readthedocs.org/projects/pavics-raven/builds/

It appears that the Raven RtD builds have been failing due to memory consumption errors for the past month. This appears to be affecting not Raven but other PAVICS birds that are built using the Anaconda image on RtD. Error output is not very helpful:
```
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... Killed
Command killed due to excessive memory consumption
```
I am currently trying to figure this out for https://github.com/bird-house/flyingpigeon on `next`. Once I can find a solution, I'll port it to here.

**Comment by tlvu** [comment]
Might want to ping the RtD dev like I did here previously https://github.com/readthedocs/readthedocs.org/issues/5847#issuecomment-519198831

**Comment by tlvu** [comment]
Also, does anyone of us receive notification when RtD build fail?  We can not react if we don't know about.

**Comment by Zeitsperre** [comment]
No. I don't mind having them sent to me. I just need to beset as co-maintainer for them on RtD.

**Comment by tlvu** [comment]
Same RtD issue observed here https://github.com/bird-house/flyingpigeon/issues/318

**Comment by Zeitsperre** [comment]
Reopening this issue since new errors have appeared as of yesterday. Now it is verbosely complaining of memory limitations. No changes were performed on the `environment.yml` with #221 after getting successive build passes. Really frustrating.

**Comment by Zeitsperre** [comment]
For more information: https://readthedocs.org/projects/pavics-raven/builds/

**Comment by tlvu** [comment]
@huard @Zeitsperre Just to be sure we can proactively catch those errors in the future, when RtD build fail, is anyone of us getting any sort of notifications?  I am not getting anything.

**Comment by huard** [comment]
You're a maintainer on pavics-raven, so can add your email in the notifications. I've just added Trevor and myself.

**Comment by tlvu** [comment]
> You're a maintainer on pavics-raven, so can add your email in the notifications. I've just added Trevor and myself.

Oh geez, I thought notification would have been automatically activated for maintainers ! 

By the way @Zeitsperre is there a trace that the `stable` image worked so we can show to the RtD dev?

**Comment by Zeitsperre** [comment]
@tlvu Yes, in the build history for `fix_220`, you can clearly see that the builds were good on Wednesday and broken on Thursday. As I said, there were no changes to the code. Is ti possible that they lowered the amount of memory allocated to their VMs? Even then, we aren't installing all that much to be build the docs. Weird.
