### ISSUE TITLE
Fix failing notebooks

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/raven#225]
## Description
Notebooks are presently broken due to an error in PyWPS that has been addressed in master (https://github.com/geopython/pywps/issues/528, https://github.com/geopython/pywps/pull/529). Notebooks need to be re-examined once a new PyWPS is available that has these fixes integrated.

## Additional Information
#223

**Comment by huard** [comment]
@Zeitsperre Another option would be to make birdy less rigid. It could tolerate that the inferred mime type does not match supported mime types. This could be done on a short time-scale.

**Comment by richardarsenault** [comment]
Does this relate to the use of Salem and it failing in "gridded_data_subset.ipynb"?

**Comment by Zeitsperre** [comment]
@richardarsenault No, that was unrelated to this. This has more to do with inputs allowed in http requests. Making a note here to return to this this coming week

**Comment by huard** [comment]
This seems fixed.
