### ISSUE TITLE
Split project into ravenpy and the WPS server

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#226]
## Description

The python wrapper should be extracted from this repo and live in its own repo. 
This repo would only contain WPS services.

**Comment by julemai** [comment]
Talked to the CSHS folks. We can get for sure a project there: https://github.com/CSHS-CWRA

I will just need to tell them from which GitHub to import. Or if they should just create an empty one with a licence (do you prefer one?) and a name (RavenPy?!).

**Comment by huard** [comment]
An empty one will do. MIT license. ravenpy. And permissions to maintain the repo.

**Comment by julemai** [comment]
I've created the new project `RavenPy` under CSHS. I just became the admin of the whole CSHS GitHub.

I gave @dustming and @richardarsenault write permissions and @huard admin permissions. Let me know whom else you'd like to have added. For now it is private but I can make it also public if you'd like to.

**Comment by huard** [comment]
Thanks! Please make it public, otherwise release could be difficult.

**Comment by julemai** [comment]
Done!
