### ISSUE TITLE
WPS for hydrological indicators (4)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#23]
EG EFlowStats
https://github.com/USGS-R/EflowStats
R package

**Comment by richardarsenault** [comment]
Simple toolbox for now, we can add more during maintenance. 

Inputs: 
-vector of streamflows (m3/s) including timestamps (NetCDF?)

Outputs: series of hydrological indicators, either in txt form or in a type of structure (NetCDF?)

WPS should calculate Min, Max and Average Streamflow for: 

1- The entire series;
2- Values per year (nYears)
3- Values per month (12 x nYears);
4- Average and standard deviation of all years from point 2 (1x1);
5- Average and standard deviation of all months from point 3 (12x1);
