### ISSUE TITLE
WPS for climatology-based ensemble streamflow predictions

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#236]
TODO: Define API

**Comment by richardarsenault** [comment]
@huard I have started a branch "climatologyESP" to do the climatology-based ESP and I hit a snag:

- test_wps_climatology_esp.py I call the WPS and you can submit one (and only one) hydrological model and send it's parameters as well. This is a string of comma-separated parameters (params).
-wps_climatology_esp receives a model_name and params. In that WPS, I instantiate the model with the get_model process.

Now, I'd like to "match" the parameter values in the input "params" string to the parameters in the model class (i.e. m.params)

Do you think you could help me out? I've been trying all sorts of methods but can't get it to work without hardcoding the model and parameter values... see line 81 in wps_climatology_eps.py.

Thanks!

**Comment by richardarsenault** [comment]
@julemai Hi, could you look at this and tell me what is not working? I get a weird message when I try to run the model:

terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 24) > this->size() (which is 22)

        **************************************************************
        Path : /tmp/tmp_6mqoh0a/exec/model/p00
        **************************************************************
The dataset and config files are here:

[Failing_raven.zip](https://github.com/Ouranosinc/raven/files/4542185/Failing_raven.zip)

Thanks!

**Comment by julemai** [comment]
@richardarsenault I'd need the "climatologyESP.nc". It only exists as a link in the folder.

**Comment by julemai** [comment]
It should be under `/tmp/tmp7uw0koro/climatologyESP.nc`?!

**Comment by richardarsenault** [comment]
Opps! There you go! sorry, not used to symbolic links like that!

[climatologyESP.nc.zip](https://github.com/Ouranosinc/raven/files/4542225/climatologyESP.nc.zip)

**Comment by julemai** [comment]
Runs like a charm on my end.

**Comment by julemai** [comment]
BTW, there shouldn't be a `StationIdx` be required if the variable read in only contains one dimension (i.e., time)

**Comment by richardarsenault** [comment]
Hmmm So I still get an error even when running Raven from CLI:
============================================================
                        RAVEN                               
 a robust semi-distributed hydrological modelling framework 
    Copyright 2008-2020, the Raven Development Team 
                    Version 2.9.2 w/ netCDF
                BuildDate Mar 13 2020
============================================================
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 24) > this->size() (which is 22)
Abandon (core dumped)

Which version of Raven are you running? I seem to recall we'Ve had that problem before, could it be related to the datetime format? I think there was something with the 00:00:00 default or...?

**Comment by julemai** [comment]
Yep. You must still be using rev240. 

The newer rev245 already give you a better error message and the rev250 and rev251 resolved it completely.

**Comment by richardarsenault** [comment]
OK then that must be it... So quick question then: Can I do a "Make raven_dev" but somehow tell git not to track these changes as there will probably be quite a few...?

**Comment by richardarsenault** [comment]
@huard I've updated to raven build 251 and get this error now:

> =========================================================
>                         RAVEN                               
>  a robust semi-distributed hydrological modelling framework 
>     Copyright 2008-2020, the Raven Development Team 
>                     Version 2.9.2 w/ netCDF
>                 BuildDate Apr 27 2020
> ============================================================
> time unit string: days since 1954-01-01
> 
> 
> ===============Exiting Gracefully==============
> Exiting Gracefully: CTimeSeries::ReadTimeSeriesFromNetCDF: time unit string is not in the format '[days/hours/...] since YYYY-MM-DD HH:MM:SS +0000' !
> Error Type: Bad input data
> ===============================================

And it runs on @julemai 's v251, so there must be something else. Any ideas?

**Comment by richardarsenault** [comment]
Update: This problem is fixed, continuing development.
