### ISSUE TITLE
GeoServer - Store high-resolution HydroLAKES routing data

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#243]

**Comment by richardarsenault** [comment]
@huard @Zeitsperre Can we do this now, or do we need to wait for @dustming's documented codes? Is that all part of the same package?

**Comment by dustming** [comment]
The product and the light version GIS toolbox are linked. The lake river routing product needs an update to support the light version of the QGIS toolbox.  I am working on finalizing the light version GIS routing toolbox and document the code.  After that, I will update the routing product to make it support the light version GIS routing toolbox.

**Comment by Zeitsperre** [comment]
WFS layers for the HydroLAKES polygons and pour points are now available on the GeoServer.

![Screenshot from 2020-05-04 15-52-48](https://user-images.githubusercontent.com/10819524/81007521-60f4ae80-8e1f-11ea-8f50-be9f73a68dc3.png)
