### ISSUE TITLE
Initial state estimation based on warm-up hindcast experiment.

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#246]
## Description

Describe what you were trying to get done or your feature request.

## Environment

* Raven version used, if any:
* Python version, if any:
* Operating System:

## Steps to Reproduce

```
Paste the command(s) you ran and the output.
```

## Additional Information

Links to other issues or sources.

**Comment by richardarsenault** [comment]
@huard I think we can close this as it's pretty much your resume() method?
