### ISSUE TITLE
User interaction notebook demo

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#250]
## Description

Notebook selects watershed from Ipyleaflet WFS plugin accessing GeoServer layer, selects weather data set
from THREDDS server using JupyterLab extension, runs RAVEN using an input form and displays the results
as interactive plotly graphic.

## Environment

* Raven version used, if any:
* Python version, if any:
* Operating System:

## Steps to Reproduce

```
Paste the command(s) you ran and the output.
```

## Additional Information

Links to other issues or sources.

**Comment by richardarsenault** [comment]
@huard Should we ask CRIM to work on this? Especially the leaflet and input form objects?

**Comment by huard** [comment]
The first part is done and integrated into birdy (show watersheds for WFS plugin). 
There are issues already opened for the climate data catalog. 
We could work on creating a form to launch Raven.

**Comment by richardarsenault** [comment]
@huard we now have a Full_process_example notebook that uses the ipyleaflet to select a basin and essentially builds and runs raven on some provided data, and analyzes it... Not sure how forms work, but we'd be ready to just pop some forms in there and this would be done.

**Comment by richardarsenault** [comment]
@huard is this something that can now be done with the solving of previous issues? Is it even necessary?

**Comment by richardarsenault** [comment]
Current setup is OK
