### ISSUE TITLE
Raven training notebooks can be executed smoothly on platform by 25 concurrent users.

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#251]
## Description

Describe what you were trying to get done or your feature request.

## Environment

* Raven version used, if any:
* Python version, if any:
* Operating System:

## Steps to Reproduce

```
Paste the command(s) you ran and the output.
```

## Additional Information

Links to other issues or sources.

**Comment by huard** [comment]
It would be useful to load the jupyterlab server and see how many users can be supported at once for training sessions and workshops using the current hardware.

**Comment by tlvu** [comment]
@huard This is urgent now or can wait after the cookiecutters?

**Comment by huard** [comment]
Not urgent.

**Comment by tlvu** [comment]
@huard For this issue, are you suggesting we bump the max parallelprocesses for Raven on Boreas to 25 and perform the test there?  And keep it at 25 if it works?  Current default was 2 only: https://github.com/geopython/pywps/blob/479bef8b2900964e8f166e4b4b969dd22faa541c/pywps/configuration.py#L91

Also Raven have a bunch of tutorials notebooks, which one should I try to execute 25 times concurrently?

**Comment by huard** [comment]
I don't really know what is needed to get it to work...

I suggest we start with simulating 25 users running "running_hmets.ipynb" and see how it goes. This will test the PyWPS component. If this goes well, we'll test other notebooks targetting THREDDS and geoserver.

**Comment by tlvu** [comment]
@tlogan2000 FYI I'll create 25 bogus users on our production Boreas to test this issue.  Don't freak you if you see this.  I'll clean up after this issue is closed.

**Comment by tlogan2000** [comment]
@tlvu ok thanks for the heads up

**Comment by tlvu** [comment]
Tested with just 5 users concurrently running `running_hmets.ipynb` I got this at the 5th user:
```
ServiceException: <?xml version="1.0" encoding="UTF-8"?>
<!-- PyWPS 4.2.2 -->
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="1.0.0">
  <ows:Exception exceptionCode="ServerBusy" locator="" >
      <ows:ExceptionText>Maximum number of parallel running processes reached. Please try later.</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```
Selecting "Restart kernel and run all cells" again worked.

So I think if we really want to support 25 concurrent users, we probably will need to bump that `parallelprocesses`  to higher than the default value 2.  Maybe 10?  But at least this shows the queue is cleared properly in "sync" mode.

I'll bump that `parallelprocesses` to 10 on Boreas and test again.

**Comment by tlvu** [comment]
@moulab88 FYI, with 25 concurrent users, I might trigger https://github.com/bird-house/birdhouse-deploy/issues/67 as well.  Sorry if you'll get alarms.

**Comment by tlvu** [comment]
@huard I manually opened 25 JupyterLab sessions using 25 different bogus users on our production https://pavics.ouranos.ca and trigger as fast as I can 25 times the `running_hmets.ipynb` notebook.  With Pywps `server.parallelprocesses` config set to 10, at the 20th user, it bombs again.  This is probably just luck but we probably need to set that config to at least haft the number of users we need to support running Raven concurrently.

In terms of generated load and performance, everything went very well.  Cpu and memory spike is very acceptable.  Will post a screenshot of Grafana dashboard once I get a good refresh of the graphs.

So I will bump `server.parallelprocesses` config to 14.  I can manually test 2 or 3 more notebooks if you like.  Let me know which ones.

**Comment by tlogan2000** [comment]
cool nice job.  are the number of concurrent processes global to all wps servers or only raven?

**Comment by tlvu** [comment]
> cool nice job. are the number of concurrent processes global to all wps servers or only raven?

@tlogan2000 
Only Raven.  There is no global wps config yet.  All other WPS are still using the default value of 2 for that `server.parallelprocesses` config.

**Comment by tlvu** [comment]
Grafana dashboard matching the manual 25 concurrent runs of `running_hmets.ipynb` I did above.  Note the server was almost idle at that moment, except for testthredds (the thick blue in the "CPU Usage per Container" graph).

![Screenshot_2020-09-29 Docker and system monitoring - Grafana](https://user-images.githubusercontent.com/11966697/94598515-08ee9680-025d-11eb-8271-351c6796f745.png)

**Comment by tlogan2000** [comment]
most of the testhredds activity in the last day or so is likely me testing new ncml aggregations
