### ISSUE TITLE
WPS for custom flood risk assessment and frequency analysis for real-time flood forecasts

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#253]
## Description

Describe what you were trying to get done or your feature request.

## Environment

* Raven version used, if any:
* Python version, if any:
* Operating System:

## Steps to Reproduce

```
Paste the command(s) you ran and the output.
```

## Additional Information

Links to other issues or sources.

**Comment by richardarsenault** [comment]
Something like this:
https://water.weather.gov/ahps2/probability_information.php?wfo=btv&gage=roun6

**Comment by richardarsenault** [comment]
@huard Not sure what I can add to this (wps_forecast_floodrisk.py) honestly. Providing a frequency analysis on a single forecast event seems pretty useless and utopic. I suggest we stop here, consider it a win for now and add graphics later.
