### ISSUE TITLE
WPS graphical representation of forecast skill (reliability, dispersion, accuracy, etc.)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#256]
## Description

Describe what you were trying to get done or your feature request.

## Environment

* Raven version used, if any:
* Python version, if any:
* Operating System:

## Steps to Reproduce

```
Paste the command(s) you ran and the output.
```

## Additional Information

Links to other issues or sources.

**Comment by richardarsenault** [comment]
Now in ravenpy directly and demoed in notebooks
