### ISSUE TITLE
WPS to perform generic forecasts from forecast weather data and initial model states.

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#261]
This WPS should take as inputs:

- initial hydrologic states (probably from the storage files but how to use them in hot-starting the model remains to be seen);
- forecast data as a netcdf with N-days x M-members for the required variables;
- model name and parameters
- other configuration tags such as linear transforms and time shifts, PET formulation, rain-snow split, latitude and elevation, etc required to run the raven model.

It will output the simulated forecasts as a N-days x M-members streamflow data netcdf. 

It should be generic in that it could then be used for the Climatology-ESP, Caspar and Geomet forecasts, as well as making assimilation and pre-processing more convenient.

**Comment by richardarsenault** [comment]
@julemai do you have a good idea on how to use a previous run's storage files to hot-start another run?

**Comment by julemai** [comment]
Raven is writing an output file `solutions.rvc`. This contains all the states of the last time step. Replace the current, for example, `raven-hmets.rvc` with the `solutions.rvc` and you will be able to start with the states you finished with.

**Comment by richardarsenault** [comment]
@huard Could you look into this, how we can manage to do this without breaking the current setup of "when run Raven --> setup rv files" by substituting another one from a previous run?

**Comment by huard** [comment]
1. Quick and dirty option: write a method that replaces the rvc file or template by the solution file.
2. Elaborate option: template initial values in emulators, parse the solution and feed the parameters to the template.

Option 2. will let also users specify initial conditions in general, which is currently not possible.

**Comment by richardarsenault** [comment]
Option 2 will enable data assimilation, a huge part of future forecasting endeavors. So i would propose that if it's not TOO bad. Thanks Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: David Huard <notifications@github.com> Date: 2020-04-29  16:01  (GMT-05:00) To: Ouranosinc/raven <raven@noreply.github.com> Cc: richardarsenault <richard.arsenault@etsmtl.ca>, Author <author@noreply.github.com> Subject: Re: [Ouranosinc/raven] WPS to perform generic forecasts from forecast weather data and initial model states. (#261) 

Quick and dirty option: write a method that replaces the rvc file or template by the solution file.
Elaborate option: template initial values in emulators, parse the solution and feed the parameters to the template.

Option 2. will let also users specify initial conditions in general, which is currently not possible.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Ouranosinc/raven/issues/261#issuecomment-621431608",
"url": "https://github.com/Ouranosinc/raven/issues/261#issuecomment-621431608",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by julemai** [comment]
I am usually not using the RVC file. I don't know how often this is changing with revisions of Raven and between different model setups. This is something we will need to keep in mind when using templates.

But definitely sounds fancy!

**Comment by huard** [comment]
I realized that it was probably good to have 1 anyway, so started with this, and wondering how numerically close should we expect results to be when restarting a run from a final state ? 
I get differences of about .1%

**Comment by richardarsenault** [comment]
Hmmm it should be exactly the same, it's basically the same run that continues. Maybe an issue with the date of the initialization (i.e. sometimes its taken at midnight (early same day) or midnight (late that day after the sim)... probably have to compare to a longer run to see exactly when the cutoff occurs

**Comment by julemai** [comment]
It should be exactly the same.

**Comment by richardarsenault** [comment]
Is the rvc file the only one that has information across time steps? Does the solution file or the rv output have other info that is required?

**Comment by julemai** [comment]
This is all the documentation says:
```
solution.rvc - the solution file
Stores the complete state of the system at the end of the simulation. This file can be used as initial conditions for a later model run. This file may also be generated at user-specified intervals du- ring simulation as a defense against computer breakdown for massive computationally-demanding models.
```

I already texted James but he's not online.

**Comment by julemai** [comment]
Talked to James. He says that it should be the same but it might be that he is not printing enough digits of some variables to the RVC. He needs to see it. @huard Could you send James the setup you are using?! Including all the data such that he can have a look. But James already said that he can't promise a quick turn-around this week.

**Comment by huard** [comment]
Ok. Will investigate a bit more on my end before that.

**Comment by huard** [comment]
Ok, my mistake, I thought I needed to start the simulation one day after the end of the last one, but it should be the same day (start of second = end of first). In this case errors are < 1E-5, which is consistent with the number of digits in the rvc file.

**Comment by julemai** [comment]
That’s great news!! You think that this precision is enough for our purpose?

**Comment by richardarsenault** [comment]
Yes I think so, i mean forecasts are full of uncertainty anyways. If we ever update raven for more digits or its not too much to ask of James then great, we should do it, but I would live well with that degree of precision. Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Julie <notifications@github.com> Date: 2020-04-29  21:11  (GMT-05:00) To: Ouranosinc/raven <raven@noreply.github.com> Cc: richardarsenault <richard.arsenault@etsmtl.ca>, Author <author@noreply.github.com> Subject: Re: [Ouranosinc/raven] WPS to perform generic forecasts from forecast weather data and initial model states. (#261) 

That’s great news!! You think that this precision is enough for our purpose?



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Ouranosinc/raven/issues/261#issuecomment-621553467",

"url": "https://github.com/Ouranosinc/raven/issues/261#issuecomment-621553467",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by huard** [comment]
I would think so, yes. 

At the moment, these are the number of state variables within current rvc files: 
- HMETS: 2
- GR4J: 2
- HBC-EC: 1
- MOHYSE: 0

But, in reality there are dozens of state variables (convolutions, snow temp, snow cover, etc) that are not exposed. I suppose we should template all state variables that end up in the WatershedStorage output ?

**Comment by richardarsenault** [comment]
Yes ideally for it to work well we'd need to have the exact same states carried over. Is that not all in the storage rv file? Like Mohyse I know has at least three state variables. If we go with the file with 0 states... How would that even work? Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: David Huard <notifications@github.com> Date: 2020-04-29  21:38  (GMT-05:00) To: Ouranosinc/raven <raven@noreply.github.com> Cc: richardarsenault <richard.arsenault@etsmtl.ca>, Author <author@noreply.github.com> Subject: Re: [Ouranosinc/raven] WPS to perform generic forecasts from forecast weather data and initial model states. (#261) 
I would think so, yes.
At the moment, these are the number of state variables within current rvc files:

HMETS: 2
GR4J: 2
HBC-EC: 1
MOHYSE: 0

But, in reality there are dozens of state variables (convolutions, snow temp, snow cover, etc) that are not exposed. I suppose we should template all state variables that end up in the WatershedStorage output ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Ouranosinc/raven/issues/261#issuecomment-621560768",
"url": "https://github.com/Ouranosinc/raven/issues/261#issuecomment-621560768",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by julemai** [comment]
Yes, all these state variables are given in the Watershed storage or ForcingFunctions files.

**Comment by richardarsenault** [comment]
these the "ForcingFunction" files, where can they be found? and can we update them during hot-starting?

**Comment by julemai** [comment]
You need to switch on “:WriteForcingFunctions” in the RVI file.

All Raven needs to restart is the RVC file (and of course forcings). So, I think, only adjustments in these files will perturb adjustments. If you want to make adjustments to forcing, you’d need to do that in the forcings file. 

I am however not entirely sure if EVERY variable that is dumped to the forcing file can be used as an input variable in the RVT file. We might need to implement some new variables if necessary.
