### ISSUE TITLE
Document the nc_index parameter in wpsio

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#263]
Some processes require the nc_index value to be set, others do not. I would like to figure out why and when they must be set, and which value to set, but the abstract is TODO.

**Comment by julemai** [comment]
I am guessing that this is the `station_idx` which is set. This one is ONLY necessary if the NetCDF variable is 2-dimensional. Means it contains besides `time` another dimension which is usually the `number of basins`. The `station_idx` then needs to be set to indicate which station should be read in.

**Comment by huard** [comment]
Correct.

**Comment by richardarsenault** [comment]
OK added.
