### ISSUE TITLE
Xclim update to test SDBA makes tests fail due to xclim package structure change

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#280]
Updating to the most recent version of Xclim to test SDBA features has caused many tests to fail due to packages being shuffled around in xclim. 
Ex: xclim.generic is now xclim.indices.generic;
xclim.streamflow --> xclim.indices.land._streamflow
and many others (fa, stats, generic, fit) aren't recognized anymore. 

I tried to fix the errors as I go but it seems I am breaking codes so I must not be selecting the right packages when replacing one with another.

The solution to this issue would be to update the xclim version and all calls to it from the Raven package.

@huard can you take a look and see if there's a quick fix?

**Comment by Zeitsperre** [comment]
@richardarsenault Do you have a branch open, so I can see what you've done thus far ?

**Comment by richardarsenault** [comment]
@Zeitsperre yes sorry, I just committed in the "bias_correction" branch. Note that some of the changes I've done seem to have broken things, so I've did some wrong manipulations here. Thanks!

**Comment by Zeitsperre** [comment]
As you say, xclim and xarray are pegged fairly far back. It might be worthwhile to update to either the most recent version of xclim or at the very least, the first version of xclim to integrate the major refactor. @huard any thoughts on the best way of approaching this?

**Comment by huard** [comment]
Create a new branch from master, update xclim to latest release and xarray to master, fix all issues, commit to devel branch. Then merge devel into the bias_correction branch. Once xarray is released, merge bias_correction into master.

**Comment by Zeitsperre** [comment]
Addressed via #281
