### ISSUE TITLE
XClim sdba problem with dataset and "get_axis_num"

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#282]
I am having a problem with the implementation of sdba. I have netcdf files taken from the Thredds server for ref, hist and sim. When I try and perform the "train" on (ref, hist), I get this error:

AttributeError: 'Dataset' object has no attribure 'get_axis_num'

It is kind of a vague error and I am not sure what I am doing wrong, here is the code snippet:

ref_data='https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/datasets/simulations/cmip5/atmos/day_MPI-ESM-LR_historical.ncml'
    fut_data='https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/datasets/simulations/cmip5/atmos/day_MPI-ESM-LR_historical+rcp85.ncml'
    hist_data='https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/datasets/reanalyses/era5.ncml'
    
    lat=45
    lon=40   
  
##### Here Careful of the ERA5 Longitude, that is why I have used a positive longitude... [0-360].

    ds = (xr.open_dataset(hist_data).sel(latitude=slice(lat + 1, lat - 1),longitude=slice(lon - 1, lon + 1), time=slice(dt.datetime(1981,1,1), dt.datetime(2010,12,31))).mean(dim={"latitude", "longitude"}, keep_attrs=True))
    ds.to_netcdf('hist.nc')
    ds2 = (xr.open_dataset(ref_data).sel(lat=slice(lat + 1, lat - 1),lon=slice(lon - 1, lon + 1), time=slice(dt.datetime(1981,1,1), dt.datetime(2010,12,31))).mean(dim={"lat", "lon"}, keep_attrs=True))
    ds2.to_netcdf('ref.nc')
    ds3 = (xr.open_dataset(fut_data).sel(lat=slice(lat + 1, lat - 1),lon=slice(lon - 1, lon + 1), time=slice(dt.datetime(2041,1,1), dt.datetime(2070,12,31))).mean(dim={"lat", "lon"}, keep_attrs=True))
    ds3.to_netcdf('fut.nc')
    
    group_month_nowindow = sdba.utils.Grouper('time.month')

    Adj = sdba.DetrendedQuantileMapping(nquantiles=50, kind='+', group=group_month_nowindow)

    Adj.train(ds,ds2) # I tried using the netcdf file path directly also, did not work.

Any help would be appreciated!

Thanks

**Comment by Zeitsperre** [comment]
Looking into this now.

**Comment by Zeitsperre** [comment]
@richardarsenault Think you could post this issue in the Xclim repo (https://github.com/Ouranosinc/xclim/issues/)? This doesn't seem to be Raven-specific and I won't be able to spend much time on this in the next two weeks.

In terms of my progress, I can't seem to replicate the errors. I keep getting DAP-related errors (which I imagine is due to my bad internet connection). Are you running these in a notebook on PAVICS infrastructure?

**Comment by richardarsenault** [comment]
User error. Replaced user, now everything works. Thanks!
