### ISSUE TITLE
Make install should update conda environment

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/raven#284]
When creating the raven environment, the requirements listed in the `environment.yml` are installed. This is fine, but when performing an installation using `make install`, the raven and ostrich tools are built and pip install is run; No calls are made to reinstall the conda environment.

This wouldn't be a problem except one dependency (`birdy`) does not have a PyPI entry and is only installable via conda. Seeing that the installation scripts are divided by initialization and installation steps (which largely install the same packages), this makes local testing/debugging a nightmare.

Proposal:
 - Call  `"$(ANACONDA_HOME)/bin/conda" env update -n $(CONDA_ENV) -f environment.yml` at the installation step.
 - Optionally: remove `"$(ANACONDA_HOME)/bin/conda" env update -n $(CONDA_ENV) -f environment.yml` from the environment initialization step.

**Comment by tlvu** [comment]
> when performing an installation using `make install`, the raven and ostrich tools are built and pip install is run; No calls are made to reinstall the conda environment.

Isn't that because we stopped depending on Conda targets?  Previously we used to have the dependency and it would have fixed this problem?

>  one dependency (`birdy`) does not have a PyPI entry

It's here under a different name can Conda: https://pypi.org/project/birdhouse-birdy/.  I also find it odd and error-prone for the Pypi and Conda package to have different name.

**Comment by huard** [comment]
Not sure what is expected of me here.

**Comment by Zeitsperre** [comment]
@huard It's more to keep you in the loop and/or weigh in on the options. I wanted to know whether you had any strong feelings on the proposal before I run with something along those lines.

**Comment by huard** [comment]
I'm not sure I understand the issue given that birdy is on pypi.

**Comment by huard** [comment]
Closing, since any issues such as this should be raised in the birdhouse-cookiecutter repo.
