### ISSUE TITLE
Reading netcdfs with xarray and taking mean of subset returns nans

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#285]
@Zeitsperre @huard In branch bias_correction, the test "test_bias_correction.py", selection and mean of subset returns nans everywhere so the codes fail. Any help would be appreciated!

**Comment by julemai** [comment]
This happens if some of the entries in the NetCDF are NaN. You could just try `np.nanmean()`.

**Comment by richardarsenault** [comment]
Hmmm I didn't realize everyone got these messages, sorry! Thanks, I can try doing that on the main array, but NRCan should not have any Nans in it. I will check!

**Comment by julemai** [comment]
No need to be sorry. My setting is that I receive all messages. Maybe it is because it is a spatial dataset and some grid cells are just not filled with values? At least that would be the case for CaSPAr data.

**Comment by richardarsenault** [comment]
The worst part is that the code is the exact same as the one used in the NRCan data test script, so I really am at a loss. I'll try and debug some more. I am extracting the points in a 2°x2°grid around a point in central Ontario, so there should be no NaNs there in NRCan 10km. I will try the nrcan code directly to see the differences.

**Comment by julemai** [comment]
Ok. Otherwise send me the NetCDF and I'll have a look

**Comment by richardarsenault** [comment]
Thanks for the offer, but it's a ncml that links to like a few GB of ncfiles... I'll try and debug some more first!

**Comment by julemai** [comment]
Sounds good! Let me know if there's something I can do

**Comment by richardarsenault** [comment]
Problem solved, it was a user error. Forgot to wrap the test suite in a class... still don't know why that changes anything but now works so I'll leave it at that. Thanks for the support :)
