### ISSUE TITLE
Xclim SDBA timeout with NRCan

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#286]
## Description

Trying to implement bias-correction of climate data using Xclim to push bias-corrected data to a raven model, to do climate change impact assessments.

The frame seems to be working, able to bias correct climate model data based on ref, fut vs NRCan as the historical data.

However, there seems to be a problem with the size of the ncml and the timeout if I use more than 10-12 years as the historical data. I get a : "Netcdf: DAP failure" error if I use too many years.

Also, will the new version of xarray (master) be pushed on the Raven GIT so we can use xclim directly or would that cause too much trouble? Just so we don't have to always switch environment.

**Comment by huard** [comment]
Is this through WPS or straight from the console ? 
Could you post an example recreating the issue ?
@tlvu Would you be able to take a look ?

**Comment by tlvu** [comment]
Sure I can take a look, probably next week.  Can I have steps to reproduce the problem?  Is it just a curl on a DAP link or something more elaborate?  Which DAP link precisely?

**Comment by richardarsenault** [comment]
yes, from the tests folder:
pytest test_bias_correction.py

It will work because I only used 10 years in the NRCan time slice (2001-01-01 to 2010-01-01). However if you change for 1981-01-01 to 2010-12-31, it fails, which I think is due to the size/timeout. You can play with the length and at some point around 12 years it always fails.

**Comment by richardarsenault** [comment]
I have now pushed a version of the test file "test_bias_correction.py" that covers 20 years of NRCan and fails, to simplify debugging. Thanks!

**Comment by richardarsenault** [comment]
Reopening as the SDBA test is still failing due to timeouts.

**Comment by tlvu** [comment]
I got the `test_bias_correction.py` working by bypassing the 2 front proxies (Nginx and Twitcher) and hitting Thredds directly.  Looks like one or both the 2 front proxies are timing out too early.  Thredds and the NCML are working fine.

**Comment by richardarsenault** [comment]
OK cool, does that mean I should change the way I access the data in my scripts and notebooks? Thanks!

**Comment by tlvu** [comment]
No I'll try to bump those timeouts as this will impact all users outside of Ouranos internal network.  I can hit Thredds directly because I am inside but this won't work for everyone else.

**Comment by richardarsenault** [comment]
OK Gotcha, thanks a lot!

**Comment by tlogan2000** [comment]
Have you experimented with dask chunk size?

**Comment by tlogan2000** [comment]
> Have you experimented with dask chunk size?

Looking at the test_bias_correction.py I don't see any `chunks` specification.  I would suggest trying something like `xr.open_dataset(hist_data, chunks=dict(time=365))`.  Chunking the data seems to be a simple trick where the the thredds server receives mutliple requests vs one large one therefore the timeout does not occur
