### ISSUE TITLE
Raven needs Feb29th but climate model outputs are on a 365-day calendar

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#298]
## Description

I'd like to run raven for climate change impact studies, meaning I need to run the model with processed precipitation and temperature from climate models. Climate models are 365-day calendars more often than not. However, when I try to run raven with that data, the model fails with "Raven cannot have blank data in precipitation time series". 

I don't know which is the best approach to this, but my feeling is that RAVEN should be able to detect that only leap-days are missing and run anyways, or at least have a flag?

@julemai any thoughts? Is it already possible to do so?

**Comment by julemai** [comment]
Raven is able to run with a 365-day calendar. Do you know which `calendar` attribute is set for the variable in the NetCDF file?

**Comment by julemai** [comment]
Raven documentations says to make following setting in RVI file:
```
:Calendar [calendar string]
```
The following options are available for `[calendar string]`:
```
(Optional) Specifies the calendar to be used. 
By default, Raven uses the standard proleptic Gregorian calendar which includes leap years. 
However, for compatibility with some climate model outputs for long- term forecasting, 
sometimes it is useful to be able to run with (e.g.,) 365 day calendars. 
Raven supports the following calendars (consistent with the NetCDF calendar convention):

- PROLEPTIC_GREGORIAN (default)
- JULIAN - ignores special leap years (every 100/400 years)
- GREGORIAN - ignores special leap years before 1583
- STANDARD - same as GREGORIAN
- NOLEAP - leap years ignored
- 365_DAY - same as NOLEAP
- ALL_LEAP - every year gets a February 29
- 365_DAY - same as ALL_LEAP
 ```

**Comment by richardarsenault** [comment]
Hi, the thing is I have 3 data arrays that I convert to datasets, then merge into a 3-variable dataset and then convert that to netcdf. I have tried adding a "calendar" attribute to '365_day' with no success. But you say that if I do it correctly, Raven should decode the calendar and run anyways?

**Comment by julemai** [comment]
Yes, if that attribute is set in the time variable, Raven will detect it and use the according calendar. Magic! :)

**Comment by richardarsenault** [comment]
Just saw the crosspost, sorry. I see "365_day" is there twice with different meanings, is that supposed to be? thanks!

**Comment by julemai** [comment]
Haha. Yeah, it's a typo. Should be `366_DAY - same as ALL_LEAP`

**Comment by julemai** [comment]
If you don't get the calendar set in the NetCDF file you could just try to set the `:calendar` in the RVI file and try if that works. I didn't do this implementation. So, I don't know. But it's worth a try I think.

**Comment by julemai** [comment]
Otherwise you could send me the NetCDF and I will have a look if you'd like.

**Comment by richardarsenault** [comment]
ok thanks, I'll try those alternatives and reach out if I get stuck again. You've already done enough :) Thanks!

**Comment by richardarsenault** [comment]
Well that wasn't long... I can either create the time attribute 'calendar' but then I get this error message from xarray:
`ValueError: failed to prevent overwriting existing key calendar in attrs on variable 'time'. This is probably an encoding field used by xarray to describe how a variable is serialized. To proceed, remove this key from the variable's attributes manually.
`

If I forego this step, the data writes fine to the netcdf, but there is no calendar. However, the time is stored as a dataarray of cftime datetimeNoLeap objects:

```
xarray.DataArray
'time'

    time: 3650

    array([cftime.DatetimeNoLeap(2070, 1, 1, 12, 0, 0, 0),
           cftime.DatetimeNoLeap(2070, 1, 2, 12, 0, 0, 0),
           cftime.DatetimeNoLeap(2070, 1, 3, 12, 0, 0, 0), ...,
           cftime.DatetimeNoLeap(2079, 12, 29, 12, 0, 0, 0),
           cftime.DatetimeNoLeap(2079, 12, 30, 12, 0, 0, 0),
           cftime.DatetimeNoLeap(2079, 12, 31, 12, 0, 0, 0)], dtype=object)


```
If you have an idea how to deal with this I'd be interested!

If you need, here is the netcdf that I am trying to get to work.

[ClimateModelFuture_ts3.nc.zip](https://github.com/Ouranosinc/raven/files/5382183/ClimateModelFuture_ts3.nc.zip)
Thanks for any feedback!

**Comment by julemai** [comment]
Hm. But the `calendar` attribute is set correctly in this file. It is set to `365_DAY`. And Raven is still complaining?

**Comment by richardarsenault** [comment]
Yes, same error. I also found an alternative way to force a calendar using: bias_corrected_met.time.encoding['calendar']='365_DAY'
instead of 
bias_corrected_met.time.attrs['calendar']='365_DAY'
which allows writing the data, but RAVEN still complains, yes. I can't get it to work at all.

**Comment by julemai** [comment]
Could you please send me the RVT file you are currently using?

**Comment by richardarsenault** [comment]
I'd like to, but it's running through the WPS server from a notebook and I think the process deletes these files upon failure so I cannot access them. I'll see if I can force something.

**Comment by julemai** [comment]
Do you know which revision of Raven you are using? It might be just a too old Raven exe. I am not able to reproduce the error but I get another one. I will need to check with James. He did currently some implementations and I think he broke some things...

**Comment by richardarsenault** [comment]
Not sure which version I am running, but it's recent enough (at least I think 251?) I'd have to ask @huard ... he would know which one we are running right now. Thanks for all your help!

**Comment by julemai** [comment]
No worries. I emailed James. He will clarify this tomorrow.

**Comment by julemai** [comment]
Hm. I get it running without any issue... Using your NC file (renamed to `Salmon-River-Near-Prince-George_meteo_daily.nc`). I am using the latest Raven version. So, I suggest two steps:

1. We check if your setup files (RVT) is comparable to what I use.
2. You let me know which Raven version you are using and I test if this is the reason that it fails.

[raven-gr4j-salmon.zip](https://github.com/Ouranosinc/raven/files/5382338/raven-gr4j-salmon.zip)

**Comment by richardarsenault** [comment]
OK thanks, that is some good info! I'll try and debug on my end to see what is happening. I'll keep you posted. Thanks!

**Comment by julemai** [comment]
Calendar related implementations were made in raven between revisions `rev167` and `rev225`. So, If you are using something before `rev225` it is likely a buggy implementation or not yet existing. I am using `rev272` which is the current trunk.

**Comment by julemai** [comment]
Revision 272 is available [here](http://www.civil.uwaterloo.ca/jmai/raven/Raven-rev272.zip)

**Comment by huard** [comment]
The raven master is at 264.

**Comment by julemai** [comment]
Tested the setup with rev264 and it runs through without any issue. So, it must be the setup.

**Comment by richardarsenault** [comment]
OK thanks for all the input, I'll try and dig deeper to find the problem. At least I know it's on my end now :)

**Comment by huard** [comment]
@richardarsenault It will be easier to debug if you just use the python wrapper (not the wps server). Look at tests/test_emulators.py for examples.

**Comment by julemai** [comment]
ohhhhh. I found the problem. The last day has blank data in your time series... I was only doing 2 year simulations (`2070-01-01` to `2072-01-01`) but if I let it run `2070-01-01` til `2079-12-31`, I get the same error. If I set the end date to `2079-12-30` it works. Means, @richardarsenault you need to fill in proper data in the NetCDF file for the last day and it should work.

**Comment by richardarsenault** [comment]
A bit of a followup summarising our discussions: Raven needs data up to 2080-01-01 00:00:00 to simulate flow until 2079-12-31, so there is missing a value. I have removed 12:00:00 from the time coordinates for testing in this netcdf: 

[ClimateModelFuture_ts4.nc.zip](https://github.com/Ouranosinc/raven/files/5385844/ClimateModelFuture_ts4.nc.zip)

Then I tried adding 12h to bring it to 'end of day'. but then the beginning period is missing the first day. It seems to me the model needs N+1 days of precip to generate N-days of flow... but I don't recall having seen this before so I'm probably missing something else entirely.

**Comment by richardarsenault** [comment]
Last value in my NetCDF precipitation. It seems to have a value for Dec-31st 2079?:

![image](https://user-images.githubusercontent.com/39815445/96150588-8579aa00-0ed8-11eb-96b1-9cd325c36e67.png)

**Comment by richardarsenault** [comment]
Last follow-up: It seems it's a bug in RAVEN, will update when it' fixed.

**Comment by julemai** [comment]
@richardarsenault @huard 

James has identified the problem. The simulation calendar needs to be set to match the calendar specified in the NetCDF file. Therefore the RVI file needs to have the following set:
```
:Calendar 365_DAY                                                                        
:StartDate             2070-01-01 00:00:00
:EndDate               2080-01-01 00:00:00
```

**Comment by huard** [comment]
This is something that we can automatically template. Opening an issue.

**Comment by richardarsenault** [comment]
This now works, closing.
