### ISSUE TITLE
Raven regionalization does not recognize nc_spec transforms for tas and pr unit changes

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#299]
## Description
A Notebook is being written that includes one possible complete workflow from selecting a point in a river and performing a hydrological model simulation on the basin using regionalization. However, the call to the regionalisation WPS fails because of the nc_spec config in RAVEN.

I've added the nc_spec IO to the WPS so it is expected, but during the model run I get the following error in the RAVEN server log:

> Traceback (most recent call last):
>   File "/home/ets/anaconda3/envs/raven/lib/python3.6/site-packages/pywps/app/Process.py", line 227, in _run_process
>     self.handler(wps_request, wps_response)  # the user must update the wps_response.
>   File "/home/ets/src/raventest/raven/raven/processes/wps_regionalisation.py", line 159, in _handler
>     **kwds)
>   File "/home/ets/src/raventest/raven/raven/utilities/regionalization.py", line 107, in regionalize
>     m(overwrite=True, **kwds)
>   File "/home/ets/src/raventest/raven/raven/models/base.py", line 403, in __call__
>     procs = self.run(ts, overwrite, **kwds)
>   File "/home/ets/src/raventest/raven/raven/models/base.py", line 384, in run
>     self.assign(key, val)
>   File "/home/ets/src/raventest/raven/raven/models/base.py", line 239, in assign
>     raise AttributeError("No configuration key named {}".format(key))
> AttributeError: No configuration key named nc_spec
> ERROR: Process._run_process(): Process error: method=wps_regionalisation.py._handler, line=159, msg=No configuration key named nc_spec

I would need help in debugging this as I have no idea how the base mechanics work.

## Steps to Reproduce
switch to Bias_correct_notebook branch
Run a local RAVEN instance;
make notebook
open the 'Full_process_example_1.ipynb' notebook
run completely. It will do it's thing and fail at running the wps.regionalisation segment.

**Comment by huard** [comment]
Pass the information inside nc_spec to the model one variable at a time: 
```
        for key, val in nc_spec.items():
            model.assign(key, val)
```
See how it's done in the `wps_raven` `_handler` method.

**Comment by richardarsenault** [comment]
Got it, thanks. I had to also add a condition to detect the presence of nc_spec in the config, but all works now.
