### ISSUE TITLE
Need to be able to pass specific state variable values during the Raven RVC resume method

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#305]
This issue is related to the 'assimilation' branch. Issue can be replicated by running pytest test_data_assimilation.py in the tests folder.

For data assimilation purposes, we need to be able to run the hydrological model using externally-computed state variables.
The chain goes like this:

1- Run the model
2- Extract the state variables of interest (here soil0 and soil1, for example)
3- Perform the assimilation
4- Update the state variables
5- Run the model on the next time step using the assimilated state variables.

Note that the only 2 or 3 out of the total list of state variables needs to be updated. 

The way I do this is as follows:
1- run the model
2- parse and read the solution.rvc file
3- extract the state variables that I need
4- perform the assimilation
5- read-in the rvc file of step 2 so it is an object in the model class
6- update the specific value in the model class, ex: model.rvc.hru_state.soil0=350 **

Step 6 is where I am blocked. I cannot update the value directly as there is no setter method for specific rvc variables. There is, however, a setter for the entire HRUStateVariables object, in rv.py, that instantiates the rvc object in the model class.:

```
    @property
    def hru_state(self):
        return self._hru_state.get(1)

    @hru_state.setter
    def hru_state(self, value):
        self._hru_state[1] = value
 
```
The problem I face is that I cannot set an attribute directly, and I cannot find a way to add a setter for a single variable in the rvc object. I've tried using the model.rvc.hru_state.soil0=XYZ and the model.rvc._hru_state.soil0=XYZ and all sorts of other combinations to try and make it work, but I always get the same message: AttributeError: can't set attribute. I've tried adding a property and setter for the variable directy but I was unsuccessful.

I imagine there MUST be a way to do so, but after a few hours of tinkering around I think I would need help from someone who understands classes better than I do.

Thanks for any comments or suggestions!

**Comment by huard** [comment]
Check file models/state.py

Method `_replace` can modify values in place. 
I can try to make this more user friendly, but for now it should work.

**Comment by richardarsenault** [comment]
This works! thanks!

Eventually it will be good if you can go through it and make it more professional, but you're right, I can now move forward.
