### ISSUE TITLE
Issue with rotated-pole coordinates in ECCC forecasts

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#307]
This issue pertains to the reading of historical forecast data (hindcasts) from ECCC, via Caspar data stored on the THREDDS server. I can access the data just fine, but there is an issue with the lat/lon coordinates. The coordinates are rotated-pole coordinates originally, (1D vectors of rlon and rlat) but to keep the data in lon/lat directly I preserved the 2D arrays of lat and lon. 

Now, my issue is that codes such as rioxarray.clip cannot use a shapefile as a mask because of this it seems. I also cannot slice using lat and lon as coordinates. But since the rlon and rlat coordinates are projected, I have no clue how (or if it's possible) to use the 1D rlon and rlat vectors and somehow reproject them during the data extraction and masking?

The issue can be seen in branch "hindcasting_caspar" and running "pytest test_hindcasting.py". There will be this error:
`rioxarray.exceptions.DimensionError: x dimension not found. 'set_spatial_dims()' can address this.
`
 I have added a line that is currently commented that solves this, but causes another error:
`rioxarray.exceptions.NoDataInBounds: No data found in bounds. Data variable: tas`
I think this might be because the method is expecting 1D coordinates but receiving 2D variables? just a hypothesis, as the shapefile is in the same domain and should detect some points.

Note that the test data is on the large side (about 72Mb), it is temporary, eventually I will read it from the server. I extracted a subset of one file to work locally for now. I did this because I had to change the lat/lon to latc/lonc for the coordinates as xarray did not me read a netcdf file that has 2D variables that are also coordinates... Thus the rebuilding of a new netcdf for testing.

If anyone has ideas on this I'd be happy to hear them, thanks!

**Comment by huard** [comment]
See the CF-convention on rotated pole coordinates. http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#grid-mappings-and-projections
For a clean solution, we'd need the grid cell corners (the cell vertices) http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#cell-boundaries

This is something we could fix using NcML, but we'll need the "bounds".

**Comment by julemai** [comment]
The CaSPAr data contain the `grid_mapping` variable. So, that shouldn't be an issue. 

Coordinates of cell corners `lath` and `lonh` can be derived for every 2D set of cell centers `lat` and `lon` using:
```
def create_gridcells_from_centers(lat, lon):

    # create array of edges where (x,y) are always center cells
    nlon = np.shape(lon)[1]
    nlat = np.shape(lat)[0]
    lonh = np.empty((nlat+1,nlon+1), dtype=np.float)
    lath = np.empty((nlat+1,nlon+1), dtype=np.float)
    tmp1 = [ [ (lat[ii+1,jj+1]-lat[ii,jj])/2 for jj in range(nlon-1) ] + [ (lat[ii+1,nlon-1]-lat[ii,nlon-2])/2 ] for ii in range(nlat-1) ]
    tmp2 = [ [ (lon[ii+1,jj+1]-lon[ii,jj])/2 for jj in range(nlon-1) ] + [ (lon[ii+1,nlon-1]-lon[ii,nlon-2])/2 ] for ii in range(nlat-1) ]
    dlat = np.array(tmp1 + [ tmp1[-1] ])
    dlon = np.array(tmp2 + [ tmp2[-1] ])
    lonh[0:nlat,0:nlon] = lon - dlon
    lath[0:nlat,0:nlon] = lat - dlat

    # make lat and lon one column and row wider such that all
    lonh[nlat,0:nlon] = lonh[nlat-1,0:nlon] + (lonh[nlat-1,0:nlon] - lonh[nlat-2,0:nlon])
    lath[nlat,0:nlon] = lath[nlat-1,0:nlon] + (lath[nlat-1,0:nlon] - lath[nlat-2,0:nlon])
    lonh[0:nlat,nlon] = lonh[0:nlat,nlon-1] + (lonh[0:nlat,nlon-1] - lonh[0:nlat,nlon-2])
    lath[0:nlat,nlon] = lath[0:nlat,nlon-1] + (lath[0:nlat,nlon-1] - lath[0:nlat,nlon-2])
    lonh[nlat,nlon]   = lonh[nlat-1,nlon-1] + (lonh[nlat-1,nlon-1] - lonh[nlat-2,nlon-2])
    lath[nlat,nlon]   = lath[nlat-1,nlon-1] + (lath[nlat-1,nlon-1] - lath[nlat-2,nlon-2])

    return [lath,lonh]
```
(the function above is for example part of the GridWeightsGenerator [here](https://github.com/julemai/GridWeightsGenerator/blob/main/derive_grid_weights.py)

Hope that helps.

Note: Some ECCC products (I think the global ones) are not in `rotated pole` projection but in `yin yang` projection. You will then find a TWO grid mapping variables in there. The above code still works but none of the variables will have a `grid_mapping` attribute since NetCDF is not yet able to accommodate [Yin-Yang](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2004GC000734) grids.

**Comment by richardarsenault** [comment]
So it turns out that the problem is due to the way I aggregated the single member, single forecast date netcdf files into monthly blocks. I will try reagregating using the same setup, metadata and attributes as the input files and see if that works. I can open the files that are directly downloaded from Caspar so I will copy the metadata on rotation and coordinates to my files and update my results here.

**Comment by richardarsenault** [comment]
Everything is working now, and for posterity: will accumulate files daily, so we get all members in one file for each day, to overcome the problem of seemingly random original grid changes from the source. So 1 per day will eliminate that problem.
