### ISSUE TITLE
Allow users to download the Land cover TIFF file after clipping with the catchment boundaries

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#317]
Users would like to be able to get the clipped land-use raster for their catchment along with the % of each land-use category. Adding this as an option out of the NALCMS zonal stats WPS would be perfect.

**Comment by Zeitsperre** [comment]
I'm fairly certain that the zonalmask functuion I used for this process returns that mask by default. I'd need to delve into the code to see how easy it would be to enable it but the implementation shouldn't be too difficult. A more difficult thing to manage is the returns; how do we return it in such a way that it doesn't break existing scripts? TBD.

Do you have a level of priority for this?

**Comment by richardarsenault** [comment]
Not very high on the priority list, but it is a feature that at least one user has manifested in a demo and would be very useful to them.

Regarding the outputs: Can we just by default not return the file unless a user wants it as an optional output? That way nothong should break? (I think...)

**Comment by Zeitsperre** [comment]
Not sure, I'd be curious to hear @huard 's thoughts on this. Having a conditional number of outputs is something that we've talked about previously.

**Comment by richardarsenault** [comment]
OK! In any case, we do something similar with the terrain_analysis, where we return the DEM and display it in the notebooks. Would it be possible to simply copy that mechanism?

**Comment by Zeitsperre** [comment]
Possibly. I seem to recall much of the code already having been written. Most of the work for me would be re-familiarizing myself with the approach I used.
