### ISSUE TITLE
Add deaccumulate option

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#319]
### RVT
The `:Deaccumulate` command, if included will take cumulative precipitation values stored in the NetCDF file (such as are output by some weather models) and convert these to precipitation rates, in mm/d.

**Comment by huard** [comment]
@richardarsenault 

With the PR, you'll be able to do: 
`model.rvt.pr.deaccumulate = True`

If you want to automate this, one option would be to set a flag into the netCDF data attribute indicating this is cumulative precip. I could then set the deaccumulate flag automatically when reading the file metadata.

**Comment by huard** [comment]
I could use 
```
GRIB_stepType:                            accum
```
as the trigger to automatically set `deaccumulate` to True. Works for you ?

**Comment by richardarsenault** [comment]
I think this is perfect for the ECCC forecasts, but could we still force it for the Caspar data, which I am unsure if they keep that info? For sure the aggregated NetCDF I created, I for sure did not provide this type of tag...

**Comment by julemai** [comment]
CaSPAr data do not have that tag. It is not part of the original data. Hence I don’t add it. Sorry!

**Comment by huard** [comment]
Ok.
If need be, we can add metadata attributes in the NcML view, so no need for Julie to change anything.
