### ISSUE TITLE
Remove or Update Singularity

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/raven#325]
I've been doing some work on raven and keep coming across this esoteric error whenever I start services:
```
/home/tjs/git/raven/raven/__init__.py:24: UserWarning: The Raven Singularity image has not been downloaded. Execute 
$ singularity pull shub://132.217.141.54/hydro/raven:latest 
```
I realize this might not be relevant anymore, seeing as most build/install processes are in the `makefile`. In any case, I wanted to see if it is still at all relevant. After installing Go and Singularity, I am greeted with this:
```
(raven) ➜  raven git:(master) singularity pull shub://132.217.141.54/hydro/raven:latest
FATAL:   While pulling shub image: error fetching image to cache: failed to get manifest for: shub://132.217.141.54/hydro/raven:latest: no response received from singularity hub
```
Does this mean that Singularity has been abandoned? If so, should we remove this? Otherwise, the image URL needs to be updated.

**Comment by richardarsenault** [comment]
Yes, singularity has been abandonned

**Comment by Zeitsperre** [comment]
Good to know. I think before we can close this issue, we need to remove the singularity module and update the installation docs accordingly. The last time I ran raven, this error was still showing up in my stdout, so let's purge this, no?

The module: https://github.com/Ouranosinc/raven/tree/master/raven/singularity

**Comment by richardarsenault** [comment]
Makes sense, I just had a talk with @huard and we agreed this could be closed but you are right, if there is clutter to remove it's probably best!

**Comment by richardarsenault** [comment]
@Zeitsperre We should probably clean this before releasing the next version?
