### ISSUE TITLE
WPS interface for the HMETS emulator (2)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#34]

**Comment by huard** [comment]
@julemai 

I noticed that with the HMETS config for RAVEN, the model returns these errors/warnings
```
line 11 in file /tmp/pywps_process_342BN5/model/raven-hmets.rvc is wrong length
line 11: 0x7ffeb597bbd0
line 12 in file /tmp/pywps_process_342BN5/model/raven-hmets.rvc is wrong length
line 12: 0x7ffeb597bbd0
```

This seems to be caused by comments at the end of the line: 
```
:UniformInitialConditions SOIL[0] 155 # x(20)/2
:UniformInitialConditions SOIL[1] 455 # x(21)/2
```
If I remove the comments, the warnings disappear. 

Also, I'm getting this error with HMETS:

`Exiting Gracefully: CmvConvolution::GenerateUnitHydrograph: negative or zero duration of unit hydrograph (bad GR4J_x4)`
which is weird because there are no references to GR4J in my model config files.

**Comment by julemai** [comment]
@huard 

Do you use the source code I’ve uploaded? The second error message got updated because I found that confusing too. I’ve run all these settings with the uploaded code version and had no issues. I can look into that this afternoon. No problem.

**Comment by huard** [comment]
@julemai 
Works with 153. See PR #43 Thanks !
No need to worry about the comment issue, it's just a detail.
