### ISSUE TITLE
nc-time-axis is required but not included in build.

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#345]
The nc-time-axis package is not included in the build and is required for running some notebooks.

**Comment by huard** [comment]
It's in client_environment.yml

**Comment by cjauvin** [comment]
It isn't in the current version though right? Only in the next one on which you're working? Because I seemed to have bumped on this problem as well (not sure).

**Comment by huard** [comment]
Correct, it's in the fix-342 branch
