### ISSUE TITLE
Having problems running notebooks because of RAVENPY_RAVEN_BINARY_PATH

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#346]
All notebooks that require running the raven binary fail with:

"Could not find raven binary in PATH, and RAVENPY_RAVEN_BINARY_PATH env variable is not set"

I have the raven executable here, which is in my path when I do printenv or echo $PATH:
/home/ets/anaconda3/envs/raven-wps/bin/raven

I have installed the ravenpy package using the pip install -with-binaries approach in the ravenpy-env environment, but since that failed I then did the same in the raven-wps env, to no avail. doing export RAVENPY_RAVEN_BINARY_PATH=/path/to/binary/ does not seem to work either, I don't see it in printenv.

Finally, I tried adding it to the path in .bashrc and in .profile, still no luck. 

If anyone has a workaround or an idea, I'd be happy to hear!

**Comment by richardarsenault** [comment]
Forgot to tag @cjauvin maybe you have a quick fix?

**Comment by cjauvin** [comment]
Weird because if you have the binaries in the `bin` of your venv it should work. When you say:
> I have installed the ravenpy package using the pip install -with-binaries approach

Is that litterally the command that you have used? Because the correct command is rather:
```
pip install ravenpy --install-option="--with-binaries"
```
(I know it's very ugly it's not my fault it's `setuptools`'!)

**Comment by richardarsenault** [comment]
Hi thanks!

Yes that is the command I used (the full one from the readthedocs page): pip install ravenpy --install-option="--with-binaries"

I followed the procedure from there. When running the notebooks I am in raven-wps venv, so I also copied the binaries there. I'll try and see if I can start afresh rather than trying to reuse and update my old environments.

**Comment by richardarsenault** [comment]
I reinstalled everything and it seems to have fixed the problem, so closing this! thanks!

**Comment by cjauvin** [comment]
Sorry to not have come back earlier about it, it's just that we released version 0.11 of RavenWPS Friday afternoon, and I thought it would probably clarify the situation (this whole past week we were juggling with many different pieces and things we overall quite unstable). This week everything should converge to a more stable situation, hopefully in time for your demo.

**Comment by richardarsenault** [comment]
Don't worry about it, I don't expect people to work on weekends! While I've been able to run some notebooks, most tests fail even though I followed the instructions on the installation page (ravenpy), including the ravenpy-testdata repo etc. There must be something else not working great with my setup, so I'll try and document step by step as soon as I can.

Great news for the demo though, that's my main worry right now. Thanks for everything!

**Comment by tlvu** [comment]
> I reinstalled everything and it seems to have fixed the problem, so closing this! thanks!

Probably related to what I found here https://github.com/Ouranosinc/raven/pull/347/commits/aaaa8a5f9ca0a8f329d1d6d4b1c289d399c8c9fa

I had to uninstall ravenpy and re-install again from scratch.  Otherwise it did not want to re-install again over the same version already installed by `environment.yml` or `requirements.txt`.
