### ISSUE TITLE
WPS interface for the MOHYSE emulator (2)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#35]

**Comment by richardarsenault** [comment]
This WPS should take as inputs: 
- Rain, snow and average daily temperature climate inputs;
- Latitude of catchment centroid
- Parameter set (10 parameters)
- Catchment area (sq. km)
- Vector of dates (day of year, 1-365) of same length as climate data vectors.

Output: Qsim (m3/s)

The code should simply take the inputs, pass them to the RAVEN implementation of MOHYSE, run the model and return the simulated streamflow.

**Comment by julemai** [comment]
Please be aware that RAVEN runs with leap years. So, day of the year should be 1-366.

But Raven doesn't really need that information. It will extract all information on dates from either the NetCDF inputs or from the RVT file.
