### ISSUE TITLE
Notebook Climatological_ESP_forecasting fails with timeout errors

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#357]
Notebook Climatological_ESP_forecasting fails with timeout errors, even with relatively small forecast durations. This is run on JupyterLabs notebooks, in the tutorial_notebooks folder.

The timeout occurs in the call to the WPS for climatological ESP forecasting, in the second cell.

**Comment by richardarsenault** [comment]
Seems this is not the case anymore, simple retest and it worked.

**Comment by richardarsenault** [comment]
Nope, still time-outing after all, this seems shaky.

**Comment by tlvu** [comment]
This one is very weird.  If I use the Raven on my dev server `lvupavics.ouranos.ca` instead of prod `pavics.ouranos.ca`, I don't have the timeout error.  But both prod and my dev server are using the exact same config and same docker image versions (using same commit of the birdhouse-deploy repo).

**Comment by tlvu** [comment]
Another notebook with similarly weird timeout error https://github.com/Ouranosinc/raven/issues/362#issuecomment-772189628
