### ISSUE TITLE
Notebook Full_Process_Example_1 fails near the end during regionalization

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#358]
The notebook "Full_Process_Example_1" fails near the end during regionalization, in cell 19:
```
______________________________
# Here is where we do the regionalization.
# TODO: Fix error related to nc_spec, not working!
resp = wps.regionalisation(ts=str(tsfile), **config)

# And get the response
# With `asobj` set to False, only the reference to the output is returned in the response. 
# Setting `asobj` to True will retrieve the actual files and copy the locally. 
[hydrograph, ensemble] = resp.get(asobj=True)
# Here is where we do the regionalization.
# TODO: Fix error related to nc_spec, not working!
resp = wps.regionalisation(ts=str(tsfile), **config)
​
# And get the response
# With `asobj` set to False, only the reference to the output is returned in the response. 
# Setting `asobj` to True will retrieve the actual files and copy the locally. 
[hydrograph, ensemble] = resp.get(asobj=True)


```
____________________________________________
 owslib.wps.WPSException : {'code': 'NoApplicableCode', 'locator': 'None', 'text': 'Process failed, please check server error log'}
---------------------------------------------------------------------------
ProcessFailed                             Traceback (most recent call last)
<ipython-input-19-1809540ca066> in <module>
      6 # With `asobj` set to False, only the reference to the output is returned in the response.
      7 # Setting `asobj` to True will retrieve the actual files and copy the locally.
----> 8 [hydrograph, ensemble] = resp.get(asobj=True)

/opt/conda/envs/birdy/lib/python3.7/site-packages/birdy/client/outputs.py in get(self, asobj)
     28         if not self.isSucceded():
     29             # TODO: add reason for failure
---> 30             raise ProcessFailed("Sorry, process failed.")
     31         return self._make_output(asobj)
     32 

ProcessFailed: Sorry, process failed.

I think @huard has an idea of what is going on?

**Comment by Zeitsperre** [comment]
@huard fixed by #374 ?
