### ISSUE TITLE
Notebook "Hydrological Hindcasting" produces poor results and dates are limited

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#359]
The hindcasts seem to be providing very little spread for a summer period, and the streamflow values are very low (i.e. 8m3/s for a large catchment). Also I've tried using other dates but it seems it is not very robust as many that I have tried have failed. We will need to mesh this with the GES Caspar dataset.

**Comment by Zeitsperre** [comment]
@huard fixed by #374 ?
