### ISSUE TITLE
Gather uses of Compute Canada at ETS and U Waterloo

### ISSUE THREAD

**Issue by tomLandry** [Ouranosinc/raven#36]
While we are engaging with Compute Canada, it would be a good idea to get experience from ETS and U Waterloo on how they use or expect to use tools and services on CC.

Prepare short interviews on major uses of the teams, covering major aspects to be delivered in the CANARIE project.

**Comment by richardarsenault** [comment]
I think the prime use of Compute Canada will be to calibrate hydrological models on a wide array of catchments, in parallel. Our models run relatively fast, but calibrating one model can take say 5-10 minutes. If you have 1000 catchments to calibrate, then it is better to parallelize the process. Simple simulations should not require using CC as they are literally in the 0-2 second range. Maybe we will want to mass-process climate model extraction, and things like that. Not sure how PAVICS will respond to that.

Ultimately, if we have more complex hydrological models later on, then it would be necessary to parallelize the simulations also. Some models (i.e. Hydrotel) can require upwards of one hour to perform a single simulation. In that case, sensitivity analysis could require using CC resources.

**Comment by richardarsenault** [comment]
@huard @tomLandry I think we can close this issue now?

**Comment by richardarsenault** [comment]
@huard I think this is not going to be used moving forward, I suggest we close this issue.
