### ISSUE TITLE
Notebook "Hydrological realtime forecast" is providing no forecast at all

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#360]
The notebook is running without error, but is providing no flow at all. Perhaps the auto-query of GEPS forecasts has halted, leaving no data?

Also, weirdly, the data seems to be 0m3/s (on the axis, as no actual curve is plotted) and the timestep goes out to 2023?

**Comment by Zeitsperre** [comment]
@huard fixed by #374 ?
