### ISSUE TITLE
User-friendly WPS using selected watershed (4)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#37]
## Description

Create a WPS with minimal user inputs: 
- Name of observation product (Livneh, NRCan, DEH data)
- Click on basin outlet to identify watershed (largest possible)
- If params are given, fine, if not, automatic calibration 
- Assume Canopex or USGS for streamflow obs
- Fetch watershed properties from other WPS_watershed_meta
- Set initial conditions (explicitly or defaults)
- Set start and end date explicitly

**Comment by richardarsenault** [comment]
@huard not sure this should be a WPS, I Think a notebook would be more appropriate, and we basically have that now? Should we close this?
