### ISSUE TITLE
Need to install new packages on the PAVICS server for notebook features

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#394]
New notebooks on the PAVICS server require packages that are not currently installed. The packages can be installed as follows:

conda install netcdf4
conda install -c conda-forge intake intake-esm gcsfs zarr

I imagine netcdf4 is installed already but I can't test because import netcdf4 fails.

This will allow connecting to the Pangeo catalogs for efficient data access.

Thanks!

**Comment by Zeitsperre** [comment]
Hey Richard,

This is doable. I just want to confirm that this is within the scope of RavenWPS and not something that needs to be addressed for the PAVICS environment in general. If this is all relevant to projects/notebooks that use RavenWPS alongside other services, it might be better to integrate these into the general environment instead. @tlvu care to confirm?

**Comment by richardarsenault** [comment]
Hi, yeah it's probably better in the general environment actually, but I have no idea where to address those more "general" issues specifically.

**Comment by tlvu** [comment]
> New notebooks on the PAVICS server require packages that are not currently installed.

@richardarsenault 
These are upcoming notebooks I guess?  The ones on `master` as of yesterday were still passing.

I guess Trevor question was if those new packages are only required for RavenWPS or both RavenWPS and Jupyter env or only Jupyter env.

**Comment by richardarsenault** [comment]
Yes these are new notebooks that I would like to add. They work on my end locally but they require these packages. I am not sure what the difference is between RavenWPS and JupyterEnv, but it is not specific to Raven so I would wager it is for JupyterEnv. Basically, it will add functionality to aquire data from the Google Cloud instead of requiring the data to be on the Ouranos THREDDS server. It will be useful for Raven users, sure, but also for other users I suspect!

**Comment by tlvu** [comment]
Will be in next Jupyter env.  I let Trevor test if these will be needed for RavenWPS (the Raven server running on PAVICS).

**Comment by tlvu** [comment]
@richardarsenault FYI intake intake-esm gcsfs zarr are available on PAVICS Jupyter env.  You'll have to shutdown and restart your Jupyter server to get the new build with these installed.

**Comment by richardarsenault** [comment]
OK awesome, thanks! It works!

**Comment by Zeitsperre** [comment]
Oh, just to get the final word in, I don't think anything in ravenWPS necessitates these libraries yet. If it isn't tied to a process, it shouldn't be added.
