### ISSUE TITLE
Watershed delineation WPS (8)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#4]
This issue will probably need to be split in smaller chunks: 

- Select delineation algorithm (Richard could provide more info on this)
- Add algo to PAVICS services (CRIM)
- Host a reference set of polygons to use as benchmark (ETS please provide reference dataset)
- Find a way to test the service automatically (return performance metric, eg [ref](http://www.cs.princeton.edu/courses/archive/spr00/cs598b/lectures/polygonsimilarity/polygonsimilarity.pdf))
- Support for WFS input (multiple inputs)

**Comment by Zeitsperre** [comment]
@richardarsenault I've looked into some of this in previous work but not in a strict scripting/programming environment.

From an open source angle, I've relied on SAGA-GIS algorithms through QGIS for sink-filling, flow accumulation, and determining water basin extents. AFAIK, there are python bindings available for the long-term-support build of SAGA-GIS (v2.3.1: https://packages.ubuntu.com/bionic/python-saga), or direct system calls (via `subprocess.run(["saga_cmd", "raster_tools", "fill_sinks", etc., etc.])`).

Do you know of any particular libraries that already perform hydrological analysis in a python environment? I'm fairly active on gis.stackexchange.com so I can begin by looking there.

**Comment by huard** [comment]
@richardarsenault What's the name of the person who did the watershed delineation work for you and François? Do you want us to reuse the same algorithm ?
@Zeitsperre Found this: https://github.com/mdbartos/pysheds
Looks simple enough.

**Comment by richardarsenault** [comment]
The Person was Camille Ouellet Dallaire from McGill. We don’t have her algorithms, but it is indeed pretty simple once you have the correct DEM. I think Trevor said it was a 2-line code. The PySheds code could do the job I think and uses the same data so it should be robust.


De : David Huard <notifications@github.com>
Envoyé : July 4, 2018 11:52 AM
À : Ouranosinc/raven <raven@noreply.github.com>
Cc : Arsenault, Richard <Richard.Arsenault@etsmtl.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Ouranosinc/raven] Watershed delineation WPS (8) (#4)


@richardarsenault<https://github.com/richardarsenault> What's the name of the person who did the watershed delineation work for you and François? Do you want us to reuse the same algorithm ?
@Zeitsperre<https://github.com/Zeitsperre> Found this: https://github.com/mdbartos/pysheds
Looks simple enough.

**Comment by huard** [comment]
pysheds seems to be in active development. I'm having trouble getting it to work with a test dem over central america (the smallest file on the hydrosheds server).

**Comment by huard** [comment]
So making some progress but hitting all kinds of snags. The pysheds test suite is thin and I feel we'll have to invest some time in the software if we're to use it. I suggest exploring other options to make an informed decision.

**Comment by huard** [comment]
Check out the branch https://github.com/Ouranosinc/raven/tree/fix_4
It's not really working at this point.

**Comment by Zeitsperre** [comment]
@huard Updates:

I've been playing around with SAGA-GIS (saga_cmd) to see how these processes would look if implemented in Python and the results are... interesting. Here's a comparison of the HYDROBASINS shapefiles (level10; in green) and the output from saga_cmd using the 15sec HydroSHEDS DEM (in pink) using default thresholds. Blacks lines suggest a reasonable overlap in boundaries:

![screenshot_2018-08-14_15-54-57](https://user-images.githubusercontent.com/10819524/44115420-da1cae04-9fdb-11e8-9e22-d909fdc3a1bf.png)

I can see this maybe working well with a fair amount of tweaking. It seems as though the threshold to correctly identify water basins needs to be heavily adjusted, especially for Quebec. How we can figure out the adjustments on-the-fly would need to be discussed.

![screenshot_2018-08-14_15-57-18](https://user-images.githubusercontent.com/10819524/44115203-3e8cbb6e-9fdb-11e8-9ff4-0a418ad476d5.png)

Problems arising from coarse DEM resolution will continue to be issues, but we can leverage SAGA's hydro conditioning algorithms to preprocess highger/better resolution DEMs is entirely possible (I used to do this often in my other work; see: http://www.saga-gis.org/saga_tool_doc/2.3.0/ta_preprocessor.html)

Overall, calculating flow directions, flow connections, junctions, strahler order for rivers, hydro basins, and river segments from a DEM of North America took around 15 mins on a 2-core VM with 4G RAM. Once I have this process written in python, I'll have better statistics. 

Did we decide not to move forward on PySheds? What other alternatives are we looking into?

**Comment by huard** [comment]
Not sure I understand correctly what you've done. Will give you a call tomorrow. 

I suggest we work with SAGA and PySheds in parallel to get some experience with both, then make a decision to invest in one or the other.

**Comment by Zeitsperre** [comment]
All good. I`ll continue testing this if I have a chance. Coding the algorithm in Python should be feasible to do tomorrow.

**Comment by richardarsenault** [comment]
Hi Guys, if you haven’t had your call already I’d like to join in, I’d like to learn about all of this.

Thanks!

Richard

De : David Huard <notifications@github.com>
Envoyé : August 14, 2018 5:13 PM
À : Ouranosinc/raven <raven@noreply.github.com>
Cc : Arsenault, Richard <Richard.Arsenault@etsmtl.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Ouranosinc/raven] Watershed delineation WPS (8) (#4)


Not sure I understand correctly what you've done. Will give you a call tomorrow.

I suggest we work with SAGA and PySheds in parallel to get some experience with both, then make a decision to invest in one or the other.

**Comment by huard** [comment]
So conclusion is that doing the delineation precisely likely requires user interaction, so we'll defer the exact delineation process to the maintenance phase. As a first step, we'll simply create a process that, given an outlet coordinations, finds from an existing database of watershed boundaries the one containing the outlet coordinates. Geoserver should be able to do this 

```
 <wfs:GetFeature service="WFS" version="1.0.0"
      outputFormat="GML2"
      xmlns:topp="http://www.openplans.org/topp"
      xmlns:wfs="http://www.opengis.net/wfs"
      xmlns="http://www.opengis.net/ogc"
      xmlns:gml="http://www.opengis.net/gml"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.opengis.net/wfs
                          http://schemas.opengis.net/wfs/1.0.0/WFS-basic.xsd">
      <wfs:Query typeName="topp:states">
        <Filter>
          <Contains>
            <PropertyName>the_geom</PropertyName>
              <gml:Point srsName="http://www.opengis.net/gml/srs/epsg.xml#4326">
                <gml:coordinates>-74.817265,40.5296504</gml:coordinates>
              </gml:Point>
            </Contains>
          </Filter>
      </wfs:Query>
    </wfs:GetFeature>
```
and we can probably code this using owslib https://geopython.github.io/OWSLib/#wfs

**Comment by richardarsenault** [comment]
@huard @Zeitsperre 

Is this item still in the works? Is it possible to do the simple version like David said here?

**Comment by Zeitsperre** [comment]
Leaving a note here pointing to the directions for compiling SAGA-GIS and building on Linux with python bindings. Will explore using SAGA in the new year, I imagine. https://sourceforge.net/p/saga-gis/wiki/Compiling%20SAGA%20on%20Linux/
