### ISSUE TITLE
Installing s3fs package on PAVICS for jupyter notebooks

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#402]
@sebastienlanglois has implemented an efficient ERA5 data access system and for it to be accessible on the Jupyter notebooks on PAVICS we would need to have the "s3fs" package installed. I have installed version 2021.08.0 and it works perfectly.

@tlvu is this something you could do? It is basically the only missing part to finish the multiple tutorial notebooks I'm working on :)

Thanks!

**Comment by tlvu** [comment]
@richardarsenault I can add this the next time we rebuild our Jupyter env.
