### ISSUE TITLE
ERROR : NetCDF error [NetCDF: Attribute not found] occured.

### ISSUE THREAD

**Issue by nbustamp** [Ouranosinc/raven#427]
## Description

Hello, 
I'm a beginner user of Raver and I try to run the model, but I got this error "ERROR : NetCDF error [NetCDF: Attribute not found] occured", however, when I check the attributes of *.nc in Python and *.rvt the attributes are fine. 

Do you have any advice?

## Environment

* Raven version used, if any: 3.5 w/ netCDF
* Python version, if any: 3.9
* Operating System: Windows

## Steps to Reproduce

```
Paste the command(s) you ran and the output.
```

## Additional Information

Links to other issues or sources.

**Comment by huard** [comment]
Please try your hand with https://github.com/CSHS-CWRA/RavenPy

The repo here is for a remote server.
