### ISSUE TITLE
#data assimilation

### ISSUE THREAD

**Issue by dingxinjun** [Ouranosinc/raven#457]
## Description

in the gr4j_cn assimilation demo notebook
data assimilation at first perturb to add noise to Precipitation Temperature and observation discharge,but it does not perturb  to potential Evapration,

## Environment

* Raven version used, if any:
* Python version, if any:
* Operating System:

## Steps to Reproduce

```
Paste the command(s) you ran and the output.
```

## Additional Information

Links to other issues or sources.

**Comment by richardarsenault** [comment]
Solved with new release of RavenC that does this processing.
