### ISSUE TITLE
Configuring Raven GDAL and Rasterio

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/raven#46]
I hoping to finalize the Raven GIS class methods in the coming weeks but I'm currently blocked on an issue.

In order to more easily perform raster masking using vectors (extracting points within the contour and setting outside pixels to NaN's) most of the literature suggests that [Rasterio](https://rasterio.readthedocs.io/en/latest/index.html) would be a robust library to perform this. Unfortunately, Rasterio and native GDAL [don't work well together]( https://rasterio.readthedocs.io/en/latest/topics/switch.html); they can't easily be installed alongside each other even with Anaconda.

My question here would be what seems like a more worthwhile goal: adding some spaghetti code methods cobbled together that seem to do an okay job for now, or [configuring](https://rasterio.readthedocs.io/en/latest/topics/configuration.html) Rasterio to to work in its own environment (hopefully its own bird) to remove a lot of boilerplate code and leverage their functionalities. Questions of time, resources, and priorities come to mind.

In the mean time, I'll be looking around for other options (system calls to bash libraries that can more or less do this). Hopefully I can find something that isn't too resource-heavy.

Thoughts?

**Comment by huard** [comment]
If we go full tilt with rasterio, what are we missing ?

**Comment by Zeitsperre** [comment]
I'll look into it. AFAIK GDAL handles a lot of GeoTIFF data handling/processing and any processes that would be using it would need to use the rasterio version. It's an "all or nothing" sort of situation; if we don't think we want to leverage traditional GDAL, we shouldn't have any problems though.

**Comment by tomLandry** [comment]
@Zeitsperre please consult with @crimbeaulima too. He use GDAL quite a bit, maybe he can advise.

**Comment by Zeitsperre** [comment]
Update: Rasterio and GDAL can be used synonymously so long as GDAL is installed via conda alongside Rasteri and so long as specific types of objects opened with one are not passed to the other (e.g. GDAL `band` objects). The only instances of Rasterio and GDAL needing to be employed at the same time is in the `wps_generic_terrain_analysis.py` process and even then the GDAL subprocess call bindings are used on file paths with no objects are passed between each other.

Rasterio has a much more pythonic API and I suggest it should be used as the standard whenever reading/writing DEMs over GDAL's python bindings. With #67 merged, this is no longer a relevant discussion.
