### ISSUE TITLE
User interface for watershed delineation service (4)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#5]
# User story
User wants to run an hydrological model on a catchment. To do that, she needs information about that catchment. She goes to the PAVICS UI and in Maps Control, selects "Watershed delineation". She then clicks on the map, which calls the `shape-selection` process from `raven`, passing a longitude, latitude tuple. With a double-click, option `collect-upstream` is set to True. The process returns a geojson object with the watershed outline, which is then displayed on the map. Hovering on the selected region  displays a panel with watershed properties. The name property can be edited by the user. These properties are provided by the `watershed-properties` process in `raven` as a `json` file. These properties, as well as the lats and lons, can be used as inputs to  `raven-gr4j-cemaneige` and `regionalization` processes. They can also be saved in the user workspace. 

- [ ] Add Watershed delineation to Map Controls widget
- [ ] Call `shape-selection` on click, passing lat, lon from click event. Store geojson output and watershed id. 
- [ ] - [ ] Call `shape-selection` on double-click, passing lat, lon from click event and `collect-upstream=True`. Store geojson output and list of watershed ids. 
- [ ] Call `watershed-properties` on click, passing `ids` of watersheds. Store json dictionary of properties. 
- [ ] On hover over the selected region, display panel showing the json property dictionary, with the name property being editable. 
- [ ] Mechanism to pass the properties and lat, long to the process launcher. 
- [ ] Add DEM from Geoserver to the list of basemaps.
- [ ] Store the geojson and properties in the user workspace.

**Comment by huard** [comment]
@richardarsenault Pourrais-tu réviser stp ?

**Comment by richardarsenault** [comment]
Ça me semble bon! Pour l'extraction des autres propriétés basées sur les contours, ça va être un autre User story, exact?

**Comment by huard** [comment]
Je suggère que tout se passe en même temps dans un seul clic, donc ça serait inclus ici. Objections ?

**Comment by richardarsenault** [comment]
Aucune objection, bien au contraire. Par contre, on devrait avoir une option en quelque part pour permettre à un utilisateur qui a déjà son shapefile d'extraire les infos du bassin. Est-ce qu'on prend la même interface?

**Comment by huard** [comment]
Je pense qu'on va se garder ça pour la maintenance. Ça va impliquer  
- [ ] Implement shapefile upload in workspace
- [ ] User selects shapefile in layer switcher : contour is displayed on interface
- [ ] User hovers on shape: triggers processes computing properties for arbitrary polygon. 

Le point 3 exige qu'on puisse calculer les propriétés des bassins on-the-fly, ce que je ne pense pas qu'on soit capable de faire dans l'année 1.

**Comment by richardarsenault** [comment]
Hmmm peut-être que j'ai mal exprimé mon idée. Disons que quelqu'un a déjà un shapefile d'un bassin et veut rouler Raven (ou faire de la régionalisation par exemple). Raven a besoin du lat/long du bassin. Si on roule en régionalisation, ça prend aussi Land Cover, etc. Un moment donné il va falloir appeler les fonctions d'extraction (slope, elevation, land Cover, etc.). 

Donc je conclus qu'on ne permettra pas, à ce stade, à un user de recevoir les propriétés physiques du bassin défini par son shapefile, mais qu'on pourra le calculer pour nos besoins, pour nos codes?

**Comment by huard** [comment]
Pour la première année, on va précalculer les propriétés sur des bassins prédéfinis (hydrosheds). L'utilisateur va sélectionner un de ces bassins et on va retourner les propriétés qu'on aura préalablement calculés. 
L'année 2, on va permettre de passer un shapefile arbitraire.

**Comment by richardarsenault** [comment]
OK je n'ai pas de problème avec ça, sauf qu'il va falloir trouver une façon de calculer les propriétés pour les 5700 bassins dans la BD pour la régionalisation...

**Comment by huard** [comment]
Oui, on ne s'en sauvera pas.

**Comment by richardarsenault** [comment]
We have decided to use Notebooks in lieu of a full-fledged GUI. Closing as now Out of Scope.
