### ISSUE TITLE
Déploiement sur serveur test

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#53]
## Description

Deploy raven on Ouranos test server

Ideally before December 14th.

**Comment by huard** [comment]
https://github.com/Ouranosinc/raven/releases/tag/0.2

**Comment by moulab88** [comment]
Now up on Medus:
http://medus.ouranos.ca:9099/wps?request=GetCapabilities&service=WPS

Need a small fix on the last line of the Dockerfile file to start the service:
CMD ["source activate wps && exec raven start -b 0.0.0.0 -c /opt/wps/etc/demo.cfg"]
