### ISSUE TITLE
Add builds based off of publicly available RAVEN source code and executables

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/raven#57]
It would be great to test via Travis CI the builds and source code available at http://raven.uwaterloo.ca/Downloads.html. This would automatically inform us if any versions online are broken. Not a major priority but this could be easily done in strict Travis or with Travis-Tox.

**Comment by julemai** [comment]
Please don’t use the source code that is distributed there. The version there doesn’t support NetCDF and some of the models yet. I have redirected the code to the URL that is given in the Makefile.

**Comment by huard** [comment]
@Zeitsperre See https://github.com/Ouranosinc/raven/issues/33#issuecomment-424192524
