### ISSUE TITLE
WPS to extract watershed properties from DEM and land use layer (8)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#6]
We absolutely need:
- [x] Area
- [x] Lat, lon coordinates of watershed centroid
- [x] Mean elevation 

Return as LiteralOutput ? A JSON dictionary ? 

Implement WPS to analyze the DEM and return multiple properties (area, slope, etc). 

Also hard-code land-use file and extract additional information (open other ticket).

**Comment by richardarsenault** [comment]
I asked Trevor to check this out, to provide a simple solution for now. Maybe we can get Travis to help out for the "connecting this stuff to PAVICS" element?

**Comment by Zeitsperre** [comment]
Working towards this with #39

**Comment by Zeitsperre** [comment]
All of these processes have been addressed in #67. Please feel free to close this once that PR is merged.
