### ISSUE TITLE
WPS for generic Raven framework (8)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#7]
Launch Raven using as input the config file describing a user-defined model structure. 
Think about how the service will handle data inputs, since they depend on the model structure.

**Comment by richardarsenault** [comment]
UWaterloo (James Craig and Julie) are providing RAVEN version 2.8.1 (last stable version) for use in PAVICS. WPS remains to be created.

**Comment by tomLandry** [comment]
I'm told that https://github.com/Ouranosinc/raven/issues/33 is almost done. This issue would be one of the logical next steps. Paging @lalondma and @davidcaron

**Comment by huard** [comment]
First working version on branch generic_raven. Needs clean-up, but seems to work.

**Comment by julemai** [comment]
Revised `generic_raven`. Is properly working now. All test cases result in the same NSE as documented in the Wiki (when modelling period is starting at 1954-01-01 and has duration of 20819 days). This should be checked automatically though.

**Comment by Zeitsperre** [comment]
@julemai For `OS_NAME` you should have a definition on your machine: `Darwin`. Is that not the case?

**Comment by julemai** [comment]
@Zeitsperre Nope, `OS_NAME` is not a function available on MacOS. That's why I used `uname`. I think that's available on all UNIX systems.

**Comment by julemai** [comment]
I was suggesting the following lines for the Makefile in the [`generic_raven`](https://github.com/Ouranosinc/raven/blob/generic_raven/Makefile) branch:

```
RAVEN_URL = http://www.civil.uwaterloo.ca/jmai/raven/raven-rev157.zip
UNAME_S := $(shell uname -s)
DOWNLOAD_CACHE = /tmp/

ifeq "$(OS_NAME)" "Linux"
  FN := Miniconda3-latest-Linux-x86_64.sh
else ifeq "$(UNAME_S)" "Darwin"
  FN := Miniconda3-latest-MacOSX-x86_64.sh
else
  FN := unknown
endif
```

**Comment by huard** [comment]
Hi @julemai 
This is what's in the generic_raven branch: https://github.com/Ouranosinc/raven/blob/38aea1121f16b5664297422fa4ded0f4e27e0624/Makefile#L16

**Comment by julemai** [comment]
Hi David @huard,

what is the best way to obtain the "working directory" of the WPS process? I mean the tmp directory where all the model output etc is written?

I would like to implement proper tests of the Raven model output at the end of the Raven tests, e.g., at the end of `test_wps_raven_gr4j_cemaneige.py`. I would like to read in the diagnostics file and check if the NSE produced is the one that we expect.

**Comment by Zeitsperre** [comment]
On second inspection, I'm not sure where OS_NAME is being declared. The method that makes the most sense is to use `ifeq "$(UNAME_S)" "Linux"`. Could this be the source of some issues?

**Comment by huard** [comment]
Even though the tests still fail on Travis-CI, I've now merged the generic_raven branch with master. So if you pull from master, you should see the changes you made to Makefile. I'll work with Trevor to get the tests working properly on Travis-CI. 

@julemai The WPS workdir is `self.workdir` inside the WPS process handler. That being said, the XML response from the WPS process should include the link to the different output objects.   

You can then use this function below to read in the XML. I suggest you add get_output to tests/common.py. 

```
def get_output(doc):
    """Read XML process response and return output dictionary."""
    output = {}
    for output_el in xpath_ns(doc, '/wps:ExecuteResponse'
                                   '/wps:ProcessOutputs/wps:Output'):
        [identifier_el] = xpath_ns(output_el, './ows:Identifier')

        lit_el = xpath_ns(output_el, './wps:Data/wps:LiteralData')
        if lit_el != []:
            output[identifier_el.text] = lit_el[0].text

        ref_el = xpath_ns(output_el, './wps:Reference')
        if ref_el != []:
            output[identifier_el.text] = ref_el[0].attrib['href']

        data_el = xpath_ns(output_el, './wps:Data/wps:ComplexData')
        if data_el != []:
            output[identifier_el.text] = data_el[0].text

    return output
```

If you just want to use the model directly (without going through the WPS server) you can also use the properties (e.g. diagnostics) of the Raven class (basic.py). 
I'll write a quick example and push that during my bus ride tonight...

**Comment by julemai** [comment]
@Zeitsperre  and @huard 
I just updated the master and was running `make test`. There are 7 tests failing. Six of  them due to `Permission denied problems`. `test_wps_caps` is failing due to another reason. Are they also failing on your systems?

**Comment by huard** [comment]
@julemai I can reproduce the same issues on my end. Unclear to me yet where this is coming from.

**Comment by huard** [comment]
I can't reproduce that failure on my end, but let's not worry too much about non-raven models (this one is the pure python gr4j).
