### ISSUE TITLE
Optimize travis build

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#77]
## Description

I think the Travis build would go faster with only one call to conda update. We could add a full_install to the Makefile and use that in the travis config. In this repo, another build of Python is downloaded due to the tests and docs dependencies.

**Comment by huard** [comment]
@cehbrecht What do you think ? 
@Zeitsperre Let's sit on this for a while. Priority is the geographic stuff.

**Comment by richardarsenault** [comment]
@huard Not sure this is related, but I'm trying to start a new build from scratch and getting the following errors:

$ make clean
Removing *.pyc files ...
rm: missing operand
Try 'rm --help' for more information.
Makefile:155: recipe for target 'srcclean' failed
make: [srcclean] Error 123 (ignored)
Makefile:59: *** "Conda is not available. Please install miniconda: https://conda.io/miniconda.html".  Stop.

//////////////////////////

$ make install

Makefile:59: *** "Conda is not available. Please install miniconda: https://conda.io/miniconda.html".  Stop.

I do have Miniconda installed, and I've never had this problem before. Usually if conda is not found it auto-downloads and installs, but now it seems to just stop. Should I remove and reinstall Miniconda?

**Comment by Zeitsperre** [comment]
I'll see if I can look at this at the end of the day. I know there were some changes to the Makefile that complicated the conda buildout. Is this on the Master branch?

**Comment by richardarsenault** [comment]
@Zeitsperre 

yes, Master branch. 

However I think it would be better if we could complete the GIS stuff before fixing this. I can wait for now but the GIS codes are the bottleneck for a few items. 

Thanks!

**Comment by Zeitsperre** [comment]
@richardarsenault Made a few edits to the `master` branch. Feel free to delete the environment you were working in and try the make processes again. It should work better now.

**Comment by richardarsenault** [comment]
Thanks, will test first thing tomorrow. Great news for the GIS PR by the way, thanks!

**Comment by richardarsenault** [comment]
OK everything is working on a fresh build now, tests are all passing. Thanks!
