### ISSUE TITLE
WPS interface for the GR4J emulator (2)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#8]

**Comment by huard** [comment]
Yes, that or the wiki.

**Comment by julemai** [comment]
I'd just add a section under:
https://github.com/Ouranosinc/raven/wiki/Technical-Notes

**Comment by huard** [comment]
Sounds good.

**Comment by julemai** [comment]
Done. 

[Link to Wiki](https://github.com/Ouranosinc/raven/wiki/Technical-Notes#raven-example-setup-for-gr4j-with-cema-neige)
