### ISSUE TITLE
Hydro_basins : finding upstream basins

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/raven#80]
## Description
Discussing with @huard and @Zeitsperre there was some difficulty using 'hydro_basins' layers to find upstream basins.  The 'Pfafstetter' code could maybe help us but I can't seem to figure it out.
However, using geopandas and numpy I have created what I think is a relatively efficient method to find upstream basins using the 'NEXT_DOWN' field in the attribute tables and iteratively finding all upstream basins from a selected start point

Test code tries to find upstream area for 'lac champlain' (red-area), 'lac saint-pierre' (pink-area) and 'lac manicouguan' (beige area):  Note - Red / lac champlain area is a sub region of what is found for lac saint-pierre.

See output in image below:
![image](https://user-images.githubusercontent.com/22454970/51936008-42f6fd80-23d5-11e9-9648-65e7b7e2b400.png)

More testing might be needed but it seems to be on the right track

## Environment
anaconda py 3.6
* Raven version used, if any:
* Python version, if any:
python 3.6
* Operating System:
windows 
## Steps to Reproduce

```
import geopandas
import numpy as np
def get_upstream_basins(gdf,id):
    up_str_mask = gdf_mainbas['NEXT_DOWN'] == id
    iter_upstream = gdf_mainbas[up_str_mask]['HYBAS_ID']
    return iter_upstream

hydro_shp = 'tests\Raven\hybas_lake_na_lev12_v1c.shp'
gdf = geopandas.read_file(hydro_shp)
test_id = {}

test_id['manic']= 7129000941
test_id['lac_champlain']= 7129001411
test_id['lac_st_jean'] = 7129003831
for tt in list(test_id.keys()):
    id_row = gdf['HYBAS_ID'] == test_id[tt]

    # get Main bassin in order to reduce number of records
    id_main_bas = gdf[id_row]['MAIN_BAS']
    # Query entire dataframe for only main basin polygons
    mask_mainbas = gdf['MAIN_BAS'] == id_main_bas.values[0]
    gdf_mainbas = gdf[mask_mainbas]

    # get upstream basins from origin
    # first iteration
    up_str_mask = gdf_mainbas['NEXT_DOWN'] == test_id[tt]
    iter_upstream = gdf_mainbas[up_str_mask]['HYBAS_ID']

    all_basins = np.asarray(iter_upstream.values)
    all_basins = list(all_basins)
    for i in all_basins:
        tmp =get_upstream_basins(gdf_mainbas,i)
        if len(tmp)>0:
            all_basins.extend(tmp.values)

    # query df rows
    df_sub = gdf_mainbas[gdf_mainbas['HYBAS_ID'] == all_basins[0]]
    for a in all_basins[1:]:
        #print(a)
        df_sub = df_sub.append(gdf_mainbas[gdf_mainbas['HYBAS_ID'] == a])
    print('writing ',tt, 'to shp')
    df_sub.to_file(r'tests\Raven\\' +tt + '.shp')
   
    # dissolve boundaries
    df_sub_dissolve = df_sub.dissolve(by='MAIN_BAS')
    df_sub_dissolve.to_file(r'tests\Raven\\' +tt + '_Dissolve.shp')




```

## Additional Information

Links to other issues or sources.

**Comment by Zeitsperre** [comment]
@tlogan2000 This is great! Using GeoPandas is a much better approach than constantly reiterating through the file, even if we were to limit the selection. The work here is essential for determining the shape/region that will be used in performing zonal statistics (average slope, land cover types) with DEMs delimited by the HydroBASINS project.

Aside, I want to mention that I looked into the `UP_AREA` field from HydroBASINS, and it contains the total area upstream (including that of the selected basin) in sq. Km.

**Comment by tomLandry** [comment]
I'm not 100% what I'm looking at, but it does look great. I want to know more!

**Comment by Zeitsperre** [comment]
@tomLandry The major challenge behind the DEM approach is that it first and foremost demands a really precise and hydrologically conditioned DEM. After that, it needs to be calculated with tools that are either a) dependent on C libraries with no python wrappers, b) have heavy/complicated overhead and configuration steps, or c) are coming from rapidly-developing/immature PyPI projects.

**Comment by richardarsenault** [comment]
I've got to say that this does indeed look promising! Seeing as the HydroBasins dataset is pretty big, how much time did it take to generate those contours iteratively? are we talking seconds or minutes...?

Great work!

**Comment by richardarsenault** [comment]
OK thanks, that seems like a reasonable approach. In the end, can we submit both the list of all sub-basins and also one merged shapefile? Reasoning being that in some future instances we might want to use distributed hydrological modelling, in which case the subdivided watersheds would be direct inputs, whereas for our lumped modelling as of now, a single polygon would be preferrable.

Also, good idea for the warning!

**Comment by tlogan2000** [comment]
See edited code example with added bit for a single polygon via dissolve boundaries...

**Comment by tlogan2000** [comment]
Original version did not include the initial selected polygon -  updated version below does
```python
import geopandas
import numpy as np
import time
start1 = time.time()
def get_upstream_basins(gdf,id):
    up_str_mask = gdf_mainbas['NEXT_DOWN'] == id
    iter_upstream = gdf_mainbas[up_str_mask]['HYBAS_ID']
    return iter_upstream


hydro_shp = '~/tests/Raven/hybas_lake_na_lev12_v1c.shp'
gdf = geopandas.read_file(hydro_shp)
test_id = {}

#test_id['manic']= 7129000941
test_id['lac_champlain']= 7129001411
#test_id['lac_st_jean'] = 7129003831
#test_id['mississippi'] = 7120047061

for tt in list(test_id.keys()):
    id_row = gdf['HYBAS_ID'] == test_id[tt]
    # get Main bassin in order to reduce number of records
    id_main_bas = gdf[id_row]['MAIN_BAS']
    # Query entire dataframe for only main basin polygons
    mask_mainbas = gdf['MAIN_BAS'] == id_main_bas.values[0]
    gdf_mainbas = gdf[mask_mainbas]
    # get upstream basins from origin #
    # first iteration
    all_basins = list(gdf_mainbas[id_row]['HYBAS_ID'].values)
    for i in all_basins:
        tmp =get_upstream_basins(gdf_mainbas,i)
        if len(tmp)>0:
            all_basins.extend(tmp.values)
    # query df rows
    df_sub = gdf_mainbas[gdf_mainbas['HYBAS_ID'] == all_basins[0]]
    for a in all_basins[1:]:
        #print(a)
        df_sub = df_sub.append(gdf_mainbas[gdf_mainbas['HYBAS_ID'] == a])
    print('writing ',tt, 'to shp')
    df_sub.to_file('~/tests/Raven/' +tt + '.shp')

    # dissolve boundaries
    df_sub_dissolve = df_sub.dissolve(by='MAIN_BAS')
    df_sub_dissolve.to_file('~/tests/Raven/' +tt + '_Dissolve.shp')

    print('elapsed time : ', time.time() - start1, 's')

**Comment by Zeitsperre** [comment]
This function has been cleaned up and is now integrated in #67. I briefly spoke about this approach with @dbyrns and @davidcaron and it might be useful to investigate using `defaultdicts` to perform upstream basin identifications.

It would also be good to create a series of lookup tables (levels 7-12, with and without lakes) with the `HYBAS_ID` and `NEXT_DOWN` fields to save on processing time. These tables could be stored in the `processes` folder as CSVs and loaded when needed.

**Comment by Zeitsperre** [comment]
Closing this issue and starting a new one since this process is now deployed on master. Thanks for the save @tlogan2000 !
