### ISSUE TITLE
Switch evap from PET_DATA to PET_OUDIN

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#88]
## Description

Hard-code Oudin evapotranspiration formula, so that users don't have to send the input time series of PET.

**Comment by huard** [comment]
Note that this modifies the outputs, so the tests results will have to be updated.

**Comment by richardarsenault** [comment]
@huard We'll handle this on our end.

**Comment by richardarsenault** [comment]
#92 fixes this issue
