### ISSUE TITLE
Support multiple params from WPS call

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#89]
## Description

At the moment parallel parameters can only be called from the Model class, not the WPS interface.

**Comment by richardarsenault** [comment]
One test fails due to the parameters not returning hydrographs in the correct order (see HBV-EC test in fix-89). I tested 3 parameter sets, with parameter sets 1 and 3 being equal. Hydrographs 2 and 3 are equal (1 and 3 are different) meaning that the parameter sets did not conserve their order.
