### ISSUE TITLE
Input dataset preparation

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#90]
We need to find a way to prepare the input data from gridded climate model data (or reanalysis, other source) to the raven format. 

1- Connect to processes from PAVICS-1 that can collect meteo data from a shapefile;
2- Download and process the data according to required dates and other parameters;
3- Write the NetCDF with the appropriate conventions including all variables required by RAVEN.

**Comment by julemai** [comment]
Some thoughts on that...

2- You don't need to cut out time periods from the data for RAVEN. It will read in only the data it requires. Let's say you can provide 1990-2019 data but only do a simulation for 2015.
3- RAVEN does not actually require a specific NetCDF format. I try to do all the implementations in RAVEN such that no pre-processing of the data is required. For example:

- data are given in UTC and not local time: use `:TimeShift` option to shift to local time
- data are given in wrong unit: use `:LinearTransform` that can help to convert, e.g., [m] to [mm] or [K] to [C]
- if you receive gridded data (means 3d- lat, lon, time) you can provide a gridded weights file that specifies the contribution of each grid cell to each subunit (e.g., HRU) of RAVEN. You don't need to cut out any subdomain etc. You could technically use the sam (global) forcing dataset to run any watershed. The only thing you have to provide is the weights file. This is a GIS operation. James has written some R-scripts using a given NetCDF file and overlays it with the shape of each subunit and creates the weights file...

The point is that we ant to minimize the computationally expensive preprocessing of forcing datasets and just make RAVEN so flexible that it can handle all the cases that would have initially required a pre-processing.

So, if you have anything that RAVEN can't handle, I would be happy to make those implementations.

**Comment by richardarsenault** [comment]
I see, and I agree that Raven can do those things, but we need to start with "fixed" rv? files and so I don't think we will be able to change them on the fly depending on the type of input dataset. I'd prefer if we have a given format for our datasets and conform to those. For the dates, yes that is true we can play with those in Raven, but lets say someone wants to do a climate change study on 2070-2010, then we should just extract those data and not the entire GCM run from 1850-2100 just because RAVEN can handle it. That was what I meant, maybe I was not clear :)

Maybe during the maintenance phase we can deploy efforts to generalize raven to a larger scope of models/parameters/hyperparameters, but for now I think we should try and keep things as simple as possible.

**Comment by huard** [comment]
The issue with gridded data and weights is that for parallel basin processing, we need to provide the weights for each region. That seemed a little bit more complicated than passing just the column index (region_id). 
But that's exactly the discussion we need to have now.

**Comment by richardarsenault** [comment]
Yes indeed. I think that since our models are lumped, the meteo data will be vector format (single column of weight=1). We can calculate this outside of Raven. Then we can build a region_id x nTimesteps matrix as the NetCDF inputs, without having recourse to the weights.

If we get to distributed modelling, then I guess the only remaining option will be to have a 3D variable: region_id X nTimesteps x Weights...

Another option is to launch the parallel computing just upstream of the Raven Call. Check the NetCDF for number of dimensions. If nDim>2, then parallel computing starts and we launch 1 Raven call per basin. In that call we'd only pass the nTimesteps x Weights matrix to Raven, so Raven would only ever see single-catchment runs. But that might complicate things for the parallel computing aspect, i.e. now system calls might be inappropriate, or maybe we should use the PyWPS parallel implementations at that stage, or whatnot. Punching above my weight class here, so take with a chunk of salt.

**Comment by julemai** [comment]
The weight file would be provided for each basin. Just similar to the preprocessing you would need to do. 

The weights basically convert whichever discretisation of the inputs to whichever discretisation of the model (HRUs, lumped, grid). It is exactly the operation you have to do when you convert the gridded data into a timeseries.

For cutting out periods of time from a full dataset: for my purposes I never want to cut out data because I would have to store the full dataset AND the cut-out dataset. I like that I can basically just use always the same dataset. This changes if you want to provide the users with the forcing data that were used.

**Comment by huard** [comment]
Agree with Julie that temporal subsetting should be delegated to Raven. That's how it works at the moment. 

For the gridded weights, the interface could accept for region_id a list of (flat_index, weight) that we could write in the rvt file. That might be less complicated than I thought.

**Comment by julemai** [comment]
I am not sure how the interface looks like that's why I can't really say anything on that. The grid weights file looks like this:

```
:GridWeights                                                                   
   #                                                                           
   # [# HRUs]                                                                  
   :NumberHRUs       7                                                  
   :NumberGridCells  24                                                 
   #                                                                           
   # [HRU ID] [Cell #] [w_kl]                                                  
   #     where w_kl is fraction of forcing for HRU k is from grid cell l=(i,j) 
   #     and grid cell index l is derived by l = (i-1) * NC + j                
   #     where i and j are the row and column of cell l respectively and       
   #     NC is the total number of columns.                                    
   #     Following contraint must be satisfied:                                
   #         sum(w_kl, {l=1,NC*NR}) = 1.0 for all HRUs k                       
   1     1    0.416533067501                           
   1    15    0.107722095454                           
   1    16    0.36656977053                           
   1    17    0.0383775214918                           
   1    19    0.00602985999575                           
   1    21    0.0647676850277                           
   2     0    0.102856848918                           
   2     1    0.0334505627711                           
   2     9    0.00180896483093                           
   2    13    0.0577007064953                           
   2    14    0.395953671258 
   ...
:EndGridWeights 
```

For the lumped models, you would have only one HRU ID. Let's say 6 grid cells of the forcings are contributing to the lumped basin, you will need to specify the grid cell number (1,15,16,17,19,21 in the example) and how much each grid cell contributes to the basin, e.g., 36% of the basin are covered by grid cell #16. 

The documentation for all this is on page 158ff ([here](http://raven.uwaterloo.ca/files/v2.9/RavenManual_v2.9.pdf)).

**Comment by richardarsenault** [comment]
@huard OK your knowledge of Raven is better than mine so if you say it's feasible, let's do that. I just think we should try and keep things reasonably simple. If it's not too complicated and more future-proof, let's go with that.

**Comment by huard** [comment]
Ideally we'd support netcdf files of both types (region, time) and (lat, lon, time). Will start working on it. 
@julemai Would you have test inputs files and expected results that I could test with ?

**Comment by julemai** [comment]
Do the examples necessarily need to be for the Salmon River and for one of our four supported models? I have the test bench for the implementations I do in Raven but it is for another catchment and model (not GR4J, MOHYSE etc). Could work on getting you all for Salmon River but would take me a bit.

**Comment by huard** [comment]
Salmon: no. 
One of the supported models: ideally. 
Is it a global model ? If yes, I can probably add it rapidly to our supported models.

**Comment by julemai** [comment]
Hm. Nope, it's a distributed version of GR4J for 20+ subcatchments of the York River. Not worth the effort I guess.

Could you get me a NetCDF (lat,lon,time) for the Salmon River? Optimally with the contribution of each grid cell to the domain of the watershed?! Otherwise I would make those values up.

**Comment by huard** [comment]
Wait, I'll start with simply taking the existing Salmon file and making copies with two dimensions (region, time), and three dimensions (lat, lon, time), with zeros everywhere expect for lat_0 and lon_0. If that works, I'm confident more realistic files will work too.

**Comment by richardarsenault** [comment]
@huard @Zeitsperre 
Hi guys, 
I was wondering if there is any news on this front? It seems that it should be possible by now to extract data from a dataset using a shapefile? I feel like this is the main blocker stopping us from demonstrating the software's capabilities to the outside world, as we have to tell users to build their own NetCDF, which in theory we should be able to do. I know there was a problem with FlyingPigeon, any news on that? Thanks

**Comment by huard** [comment]
We've decommissionned the old FP and should be able to deploy the new version this week or the next.

**Comment by richardarsenault** [comment]
@huard I think we can close this one based on the recent notebooks?

**Comment by huard** [comment]
Let's merge the notebooks first and link the PR to this issue.

**Comment by richardarsenault** [comment]
I think our notebooks for ERA5/NRCan/Canopex are robust enough now to close this issue
