### ISSUE TITLE
Calling Raven WPS through Birdy crashes if identifiers have dashes

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#93]
@huard We will eventually need to remove all dashes and replace with underscores in the identifiers. Only alphanumeric and underscores are allowed as per namedtuple documentation. I started a branch so we can test the calls to the local WPSClient, branch "birdy_raven_calls"

**Comment by huard** [comment]
In principle birdy has a sanitize process that replaces dashes with underscores. Could you point me to an example where it doesn't work.

**Comment by richardarsenault** [comment]
It seems the sanitize process sanitizes the processOutputs and processInputs, but not the identifier. I've sent you an e-mail with a test-case and analysis. Maybe the problem is on my side if it works for you.

**Comment by huard** [comment]
Install birdy from git master, that should solve it.

**Comment by richardarsenault** [comment]
Now works with Birdy version 0.6.0
