### ISSUE TITLE
Shape properties don't match

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#97]
## Description

Why is the area computed by generic-shape-property so different from the Superficie attribute ?

For example, compare the test_wps_generic_shape_properties the calculated area with the superficie attribute.

**Comment by Zeitsperre** [comment]
The superficie attribute is an artifact. My suggestion is to ignore it. If we want, I can scrub that data from the shapefile. I should mention though that there will always be variation in some values for similar projections. 

For instance, Quebec Lambert (epsg 32198 or 6622) underestimates perimeter by around 10Km and area by around 400 sq Km versus WGS84/eliipsis calculation. I can try finding a better projection for the area if we want as well.

**Comment by huard** [comment]
Got it. I think what matters is that our public examples and tests are reasonably clean. I this case I think our test suite could just use a synthetic shape rather than one stored on disk.

**Comment by Zeitsperre** [comment]
I could just define a `Shape` with a series of coordinates in the test itself or make something on [GeoJSON.io](http://geojson.io/#map=2/20.0/0.0).

**Comment by huard** [comment]
A basic series of coordinates would work well.

**Comment by Zeitsperre** [comment]
Sounds good. I just need to know how to pass an in-memory JSON via WPS when it asks for an URI.

**Comment by huard** [comment]
It's done with a POST request. Look at pywps/tests/test_complexdata_io.py for an example. 

You need to create an owslib.wps.ComplexDataInput object, where data would be the string representation. 
```
wps = WPSExecution()
doc = wps.buildRequest('test-fmt',
                       inputs=[('complex', ComplexDataInput(data, mimeType=fmt.mime_type,
                                                            encoding=fmt.encoding))],
                       mode='sync')
resp = client.post_xml(doc=doc)
assert_response_success(resp)
```

**Comment by Zeitsperre** [comment]
I found a workaround using a staticmethod: 

```
    def make_shape():
        shp_definition = {
            "type": "FeatureCollection",
            "features": [
                {
                    "type": "Feature",
                    "properties": {},
                    "geometry": {
                        "type": "Polygon",
                        "coordinates": [
                            [
                               ...
                            ]
                        ]
                    }
                }
            ]
        }

        temp = tempfile.NamedTemporaryFile(suffix='.json')
        with open(temp.name, 'w') as f:
            json.dump(shp_definition, f)
        return temp
```

Which method should I apply? I imagine I could also test for both.

**Comment by huard** [comment]
I think it would be good to have an example that passes raw data. I suggest `geojson.Polygon(coords)` to keep it short.

**Comment by Zeitsperre** [comment]
@huard I opened a branch for this yesterday called `fix_97` but i don't have time to work on this until next week. All it really needs are valid polygon geocoordinates.
